class_name CombatManager
extends RefCounted
## The combat engine: turn loop, energy, banked-Swag economy, draw/discard, an encounter
## of one-or-more enemies with their own intents, targeting, and win/lose. Pure logic
## (no UI) so it can be unit-tested headless. A view connects to `changed` and re-renders.

signal changed
signal combat_ended(victory: bool)
## Fired just before an enemy resolves its intent (only when step_delay > 0), so the
## view can wind up / lunge the acting enemy before its hit lands.
signal enemy_acting(index: int, intent: Dictionary)
## Fired by the "peek" op with the titles (top-of-pile first) so the view can
## flash them; the same info also lands in the log for headless runs.
signal peeked(titles: Array)
## Fired by the "peek_pick" op (only when a view is attached, step_delay > 0)
## with the next cards (top-of-pile first); the view shows a modal picker and
## answers with resolve_pick(index). Headless runs auto-take the top card.
signal pick_requested(cards: Array)
## Fired when the Goon squad lands a hit (end of turn, or commanded by a card)
## so the view can lunge the crowd at its victim.
signal goons_attacked(enemy_index: int, dmg: int)

enum State { PLAYER_TURN, ENEMY_TURN, WIN, LOSE }

const HAND_SIZE := 5
const HAND_CAP := 10            # retained cards + draws never exceed this
const MAX_ENERGY := 3
const LOG_KEEP := 6

const THRESHOLD_DAMAGE := 6
const THRESHOLD_DRAW := 12
const THRESHOLD_PIERCE := 18
const THRESHOLD_ENCORE := 24    # spotlight line (P3 Commit to the Bit)
const SWAG_DAMAGE_BONUS := 2
const BOOED_LOSS := 4           # soft floor: falling out of the spotlight stings, doesn't cascade

# Gen-Z display names for the internal status keywords.
const _DISP := {&"strength": "Rizz", &"vulnerable": "Cooked", &"weak": "Mid", &"burn": "Roasted", &"undead": "Goons", &"jinx": "Jinxed", &"frail": "Exposed", &"poison": "Toxic"}

var state: State = State.PLAYER_TURN
var player: Combatant
var enemies: Array[Combatant] = []
var target_index := 0
var turn := 0

## Seconds between enemy actions during the enemy turn. 0 (default) resolves the whole
## turn synchronously in one call — headless tests and the balance sim rely on that.
## The view sets ~0.45 so each enemy telegraphs, lunges, and lands its hit as its own
## visible beat. Guarded awaits: with step_delay == 0 no await ever executes, so the
## synchronous contract is untouched.
var step_delay := 0.0

var energy := 0
var max_energy := MAX_ENERGY
var swag := 0
var drip := 0
var spells_this_turn := 0

# --- The Critic: style fingerprint (see compute_show_rating / style_signature) ---
var peak_swag := 0          # high-water mark of Aura reached this fight
var finisher_clean := false # a finisher (Aura cash-out) landed the killing blow
var finisher_kind: StringName = &""   # which cash-out did it (swag_x3/encore/spread/drain)
var aoe_plays := 0          # cards that hit all enemies (spread style)
var single_plays := 0       # cards that hit one target (single-target style)
var flexed := false         # took a hit while hoarding above the pierce line (a risky flex)
var pose_swag := 0          # Aura ACTIVELY generated by Pose cards (not passive drip)
var peak_undead := 0        # high-water Goon count this fight (the Swarm fingerprint)

# --- Commit to the Bit (P3) ----------------------------------------------
var encore := 0             # turns held in the spotlight (>= THRESHOLD_ENCORE)
var booed := false          # fell out of the spotlight last turn-start

var draw_pile: Array[CardData] = []
var hand: Array[CardData] = []
var discard_pile: Array[CardData] = []
var retain_hand := false        # set by the "retain" op; consumed at end_turn
var pending_pick_n := 0         # how many top-of-pile cards a "peek_pick" laid out
var pose_strike_used := false   # fan_behavior relic: first Pose per turn triggers the Goons
var summoned_ids := {}          # summon_ally "once" bookkeeping: id -> true (per fight)

var passives: Array[StringName] = []
# Gold-thief fights (The IRS): the player's purse, seeded by the view from
# GameState and synced back after _finish — the manager itself stays pure.
var player_gold := 0
var enemy_dmg_scale := 1.0
var enemy_hp_scale := 1.0
var upgrades: Dictionary = {}        # card_id -> "cost"|"value" (legacy true == "cost")
var crit_chance := 0.0
var last_crit := false
var log_lines: Array[String] = []

# --- setup ---------------------------------------------------------------

func start_combat(p: Combatant, encounter: Array, deck: Array[CardData], drip_value: int, deterministic := false, outfit_passives: Array[StringName] = [], hp_scale := 1.0, dmg_scale := 1.0, card_upgrades: Dictionary = {}) -> void:
	player = p
	enemies.clear()
	enemy_hp_scale = hp_scale
	for edata in encounter:
		enemies.append(_make_enemy(edata))
	target_index = 0
	enemy_dmg_scale = dmg_scale
	drip = drip_value
	passives = outfit_passives
	upgrades = card_upgrades
	_compute_crit()
	draw_pile = deck.duplicate()
	if not deterministic:
		randomize()
	draw_pile.shuffle()
	hand.clear()
	discard_pile.clear()
	turn = 0
	log_lines.clear()
	peak_swag = 0
	finisher_clean = false
	finisher_kind = &""
	aoe_plays = 0
	single_plays = 0
	flexed = false
	pose_swag = 0
	peak_undead = 0
	encore = 0
	booed = false
	summoned_ids = {}
	state = State.PLAYER_TURN
	_apply_combat_start_passives()
	peak_swag = swag                 # seed the high-water mark after outfit seeding
	var names := []
	for e in enemies:
		names.append(Loc.t(e.display_name))
	_say(Loc.t("the opps pulled up: %s") % ", ".join(names))
	_start_player_turn()

func has_passive(id: StringName) -> bool:
	return id in passives

# Crit chance from passives named "crit_<percent>" (e.g. crit_15 = +15%).
func _compute_crit() -> void:
	crit_chance = 0.0
	for p in passives:
		var s := String(p)
		if s.begins_with("crit_"):
			crit_chance += float(s.substr(5)) / 100.0

# Current crit chance including The Rizzard's dynamic Rizz scaling.
func live_crit_chance() -> float:
	var cc := crit_chance
	if has_passive(&"rizz_crit"):
		cc += player.status(&"strength") * 0.04   # was 0.05 — pass #4 top-end shave
	cc -= player.status(&"jinx") * 0.10
	return max(0.0, cc)

func _apply_combat_start_passives() -> void:
	if has_passive(&"energy_plus_1"):
		max_energy += 1
	if has_passive(&"start_block_5"):
		player.block += 5
	if has_passive(&"swag_start_3"):
		swag += 3
	# artefact passives
	if has_passive(&"swag_income_2"):
		drip += 2
	if has_passive(&"strength_start_2"):
		player.add_status(&"strength", 2)
	if has_passive(&"enemies_start_vulnerable"):
		for e in enemies:
			e.add_status(&"vulnerable", 1)
	if has_passive(&"borrowed_drip"):
		# borrowed_designer relic: a fat head start in an uninsured fit.
		swag += 12
		player.add_status(&"frail", 2)
	for pas in passives:
		var ps := String(pas)
		if ps.begins_with("undead_start_"):
			player.add_status(&"undead", int(ps.substr(13)))
		elif ps.begins_with("poison_start_"):
			for e in enemies:
				e.add_status(&"poison", int(ps.substr(13)))

# --- targeting -----------------------------------------------------------

func living_enemies() -> Array[Combatant]:
	return enemies.filter(func(e): return not e.is_dead())

func target() -> Combatant:
	if target_index < enemies.size() and not enemies[target_index].is_dead():
		return enemies[target_index]
	for i in enemies.size():
		if not enemies[i].is_dead():
			target_index = i
			return enemies[i]
	return null

func set_target(i: int) -> void:
	if i >= 0 and i < enemies.size() and not enemies[i].is_dead():
		target_index = i
		_emit()

func all_dead() -> bool:
	return living_enemies().is_empty()

# --- Swag economy --------------------------------------------------------

func gain_swag(amount: int) -> void:
	swag = max(0, swag + amount)
	peak_swag = max(peak_swag, swag)

func swag_damage_bonus() -> int:
	return SWAG_DAMAGE_BONUS if swag >= THRESHOLD_DAMAGE else 0

func swag_extra_draw() -> int:
	return 1 if swag >= THRESHOLD_DRAW else 0

func swag_pierces() -> bool:
	return swag >= effective_pierce_line()

## backstage_pass relic moves the pierce BENEFIT down to 12; the Critic's grading
## lines (thresholds_lit / compute_show_rating) stay at the canonical 6/12/18/24.
func effective_pierce_line() -> int:
	return 12 if has_passive(&"pierce_at_12") else THRESHOLD_PIERCE

# --- turn loop -----------------------------------------------------------

func _start_player_turn() -> void:
	state = State.PLAYER_TURN
	spells_this_turn = 0
	pose_strike_used = false
	# Ghosted never banks across turns: hard wipe, deliberately not part of _decay.
	player.statuses.erase(&"evade")
	turn += 1
	var pois := _tick_poison(player)
	if pois > 0:
		_say(Loc.t("you're Toxic'd for %d") % pois)
		if player.is_dead():
			_finish(false)
			return
	energy = max_energy
	var before := swag
	gain_swag(drip)
	_tick_powers()
	# Commit to the Bit: holding above the spotlight builds an Encore; sliding back
	# under it (a mistimed cash-out or an enemy knocking you down) gets you booed.
	booed = false
	if swag >= THRESHOLD_ENCORE:
		encore += 1
		_say(Loc.t("ENCORE ×%d — the crowd wants MORE") % encore)
	elif encore >= 2:
		if has_passive(&"no_boo"):
			# velvet_rope relic: leaving the spotlight resets Encore but never boos.
			encore = 0
			_say(Loc.t("Velvet Rope: you left the spotlight on YOUR terms"))
		else:
			# Only a REAL built-up Encore (2+) being lost boos you — a 1-turn spotlight
			# touch that you immediately cash out is not a flop. (Pass #2.)
			var lost: int = min(swag, BOOED_LOSS)
			swag = max(0, swag - lost)
			encore = 0
			booed = true
			_say(Loc.t("BOOED OFF — you fell out of the spotlight (-%d Aura)") % lost)
	elif encore > 0:
		encore = 0   # brief touch, no penalty
	if has_passive(&"strength_at_10_swag") and swag >= THRESHOLD_DRAW:
		player.add_status(&"strength", 1)
		_say("Catwalk Heels: +1 Rizz")
	if has_passive(&"heal_3_per_turn") and turn > 1:
		player.heal(3)
	var draw_n := HAND_SIZE + swag_extra_draw()
	if has_passive(&"draw_plus_1"):
		draw_n += 1
	_draw(draw_n)
	if drip > 0:
		_say(Loc.t("— Your turn %d  (+%d aura, now %d) —") % [turn, swag - before, swag])
	else:
		_say(Loc.t("— Your turn %d —") % turn)
	_emit()

## Persistent Power-card effects, applied at the start of each player turn.
func _tick_powers() -> void:
	var ritual := player.status(&"ritual")          # ramp Rizz each turn
	if ritual > 0:
		player.add_status(&"strength", ritual)
		_say("locked in: +%d Rizz" % ritual)
	var engine := player.status(&"aura_engine")      # bonus Aura each turn
	if engine > 0:
		gain_swag(engine)
	var hive := player.status(&"hive_mind")          # raise goons each turn
	if hive > 0:
		player.add_status(&"undead", hive)
		_say(Loc.t("the squad multiplies: +%d Goon") % hive)
	var barrier := player.status(&"barrier")         # standing Block each turn
	if barrier > 0:
		player.block += barrier

func card_cost(card: CardData) -> int:
	return max(0, card.cost - (1 if upgrade_mode(card) == "cost" else 0))

## Mirrors GameState.upgrade_mode: "cost" (1 cheaper), "value" (+2 amounts), "" (none).
## Legacy saves stored `true`, which reads as "cost".
func upgrade_mode(card: CardData) -> String:
	if not upgrades.has(card.id):
		return ""
	return "value" if str(upgrades[card.id]) == "value" else "cost"

## A value-Glow'd card plays with +2 on its damage/Block/heal amounts.
func _effective_effects(card: CardData) -> Array:
	if upgrade_mode(card) != "value":
		return card.effects
	var out: Array = []
	for e in card.effects:
		var d: Dictionary = e.duplicate()
		if String(d.get("op", "")) in ["damage", "damage_all", "block", "heal", "damage_if_status"]:
			d["amount"] = int(d.get("amount", 0)) + 2
		out.append(d)
	return out

func can_play(card: CardData) -> bool:
	return state == State.PLAYER_TURN and energy >= card_cost(card) and swag >= card.swag_cost

func play_card(card: CardData) -> bool:
	if not can_play(card) or card not in hand:
		return false
	energy -= card_cost(card)
	hand.erase(card)
	discard_pile.append(card)

	var swag0 := swag
	if card.swag_gain > 0:
		gain_swag(card.swag_gain)
		pose_swag += card.swag_gain
		if has_passive(&"pose_plus_1"):
			gain_swag(1)
			pose_swag += 1
		# fan_behavior relic: the FIRST Pose each turn commands an immediate Goon strike.
		if has_passive(&"goons_strike_on_pose") and not pose_strike_used and player.status(&"undead") > 0:
			pose_strike_used = true
			_say(Loc.t("FAN BEHAVIOR — the crowd rushes the stage"))
			goon_strike()

	var tgt := target()
	var is_attack := card.type == "Attack"
	_classify_play(card)
	var first_spell := spells_this_turn == 0
	var pierced := is_attack and first_spell and swag_pierces()
	var atk_bonus := swag_damage_bonus() if is_attack else 0
	if is_attack and first_spell and has_passive(&"first_spell_plus_3"):
		atk_bonus += 3
	last_crit = is_attack and randf() < live_crit_chance()
	# Aura-cost cards (mini-finishers): the spend lands AFTER the threshold snapshot
	# above (pierce/bonus read the pre-spend bank — same precedent as finishers) and
	# BEFORE effects resolve. Never counts as pose_swag, never lowers peak_swag.
	if card.swag_cost > 0:
		swag = max(0, swag - card.swag_cost)
	var ctx := {
		"source": player,
		"target": tgt,
		"enemies": enemies,
		"combat": self,
		"passives": passives,
		"bonus_damage": atk_bonus,
		"pierce": pierced,
		"crit": last_crit,
	}

	var hp0 := _total_enemy_hp()
	var pblk0 := player.block
	var tburn0 := tgt.status(&"burn") if tgt != null else 0

	var enemy_hp_before: Array = []
	for e in enemies:
		enemy_hp_before.append(e.hp)

	var normal: Array = []
	for e in _effective_effects(card):
		if String(e.get("op", "")).begins_with("finisher"):
			_resolve_finisher(e, ctx)
		else:
			normal.append(e)
	EffectResolver.apply(normal, ctx)

	# Enrage: an enemy that got hit this card gains Strength.
	for i in enemies.size():
		var en := enemies[i]
		if not en.is_dead() and en.data != null and en.data.enrage > 0 and en.hp < int(enemy_hp_before[i]):
			en.add_status(&"strength", en.data.enrage)
			_say(Loc.t("%s is ENRAGED: +%d Rizz") % [Loc.t(en.display_name), en.data.enrage])

	if is_attack:
		spells_this_turn += 1

	var tburn1 := tgt.status(&"burn") if tgt != null else 0
	if last_crit:
		_say(Loc.t("CRIT! that's lethal rizz"))
		if has_passive(&"crit_refund_energy"):
			energy = mini(max_energy, energy + 1)
		# The Rizzard's crit IS its flex: a clean crit serves Aura (active, not drip),
		# welding the crit kit to the Critic's grade so Rizz engages the USP. (Pass #2.5)
		if has_passive(&"swag_on_crit"):
			gain_swag(1)
			pose_swag += 1
	_log_card(card, hp0 - _total_enemy_hp(), player.block - pblk0, tburn1 - tburn0, swag - swag0, pierced)
	if all_dead():
		_finish(true)
	_emit()
	return true

## Finishers spend ALL banked Aura for a burst. Each one is a distinct "cash-out
## style" so WHICH finisher you close on becomes part of the Critic's fingerprint.
func _resolve_finisher(e: Dictionary, ctx: Dictionary) -> void:
	var tgt: Combatant = ctx.get("target")
	var bonus := int(ctx.get("bonus_damage", 0))
	var pierce := bool(ctx.get("pierce", false))
	var spent_swag := swag
	var crit := bool(ctx.get("crit", false))
	var boost := 1.5 if has_passive(&"finisher_boost") else 1.0   # "flash" outfit persona
	match String(e.get("op", "")):
		"finisher_swag_x3":
			if tgt == null:
				return
			_finisher_hit(tgt, int(swag * 3 * boost) + bonus, crit, pierce)
			swag = 0
			_mark_finisher(&"swag_x3")
		"finisher_encore":
			if tgt == null:
				return
			# Take a Bow: the longer you held the spotlight, the bigger the bow.
			_finisher_hit(tgt, int(swag * (2 + encore) * boost) + bonus, crit, pierce)
			swag = 0
			encore = 0
			_mark_finisher(&"encore")
		"finisher_spread":
			# Encore for the Fans: spend it all across the whole room.
			var per := int(swag * 1.5 * boost) + bonus
			for en in enemies:
				if not en.is_dead():
					var d := EffectResolver.compute_damage(per, player, en)
					if crit:
						d *= 2
					en.take_damage(d, pierce)
			swag = 0
			_mark_finisher(&"spread")
		"finisher_drain":
			# Soak It In: a smaller cash-out that heals you for half of what it deals.
			if tgt == null:
				return
			var dealt := _finisher_hit(tgt, int(swag * 2 * boost) + bonus, crit, pierce)
			player.heal(int(dealt / 2.0))
			swag = 0
			_mark_finisher(&"drain")
		_:
			push_warning("[CombatManager] unknown finisher: " + String(e.get("op", "")))
	# royalties relic: a finisher that actually spent the bank refunds a quarter of it.
	# Refund is NOT pose_swag — the Critic only credits Aura you actively performed for.
	if has_passive(&"finisher_refund_25") and swag < spent_swag:
		var refund := int(spent_swag * 0.25)
		if refund > 0:
			gain_swag(refund)
			_say(Loc.t("Royalties: the hit keeps paying (+%d Aura)") % refund)

func _finisher_hit(tgt: Combatant, raw: int, crit: bool, pierce: bool) -> int:
	var dmg := EffectResolver.compute_damage(raw, player, tgt)
	if crit:
		dmg *= 2
	var before := tgt.hp
	tgt.take_damage(dmg, pierce)
	return before - tgt.hp

func _mark_finisher(kind: StringName) -> void:
	finisher_kind = kind
	if all_dead():
		finisher_clean = true   # the Aura cash-out landed the killing blow

# Classify a played card as spread (hits all) or single-target, for the fingerprint.
func _classify_play(card: CardData) -> void:
	var is_aoe := false
	var is_single := false
	for ef in card.effects:
		var o := String(ef.get("op", ""))
		if o == "damage_all" or o == "finisher_spread" or o == "apply_status_all" \
				or (o == "damage_x_status" and bool(ef.get("all", false))):
			is_aoe = true
		elif o.begins_with("damage") or o == "sacrifice_strike" or o.begins_with("finisher"):
			is_single = true
	if is_aoe:
		aoe_plays += 1
	elif is_single:
		single_plays += 1

# --- The Critic: show rating ---------------------------------------------

## How many Aura thresholds (6/12/18) the player's peak this fight lit up.
func thresholds_lit() -> int:
	var lit := 0
	for t in [THRESHOLD_DAMAGE, THRESHOLD_DRAW, THRESHOLD_PIERCE]:
		if peak_swag >= t:
			lit += 1
	return lit

## The Critic's verdict, graded PRIMARILY on how boldly the Aura economy was played:
## peak reached, which thresholds were lit, and whether the kill was a clean cash-out.
## S = lit all three AND finished on a cash-out; A = lit all three, or two + a clean
## finisher; B = lit at least one; C = never crossed a threshold. Works mid-fight too
## (reads the current peak), so the rating can tick up live as the show builds.
func compute_show_rating() -> Dictionary:
	var lit := thresholds_lit()
	# S demands a BOLD tell — not just fat passive income coasting to lit-3 and
	# dumping. You either flexed (took a hit while hoarding past pierce) or held the
	# 24 spotlight (Encore). Coasting clean finishers cap at A. (Balance pass 2026-06-07.)
	# Bold tells (the S gate). Hoard/ramp lines flex or hold the spotlight. Tempo/wide
	# lines earn S a different way: an ACTIVE, decisive show that closes clean — either
	# wide (>=2 AoE plays) or a lot of self-generated Aura (pose_swag, not passive drip).
	# This can't be farmed by coasting on drip (pose_swag from drip is 0, AoE must be played).
	var bold := flexed or encore >= 1 or (finisher_clean and (aoe_plays >= 2 or pose_swag >= 12))
	# Pass #3 (re-earn S now that block works): S also demands the show actually
	# PEAKED into the spotlight (24), not merely simmered to lit-3 (18) and dumped.
	# Wide/flex/active builds still reach S — they just have to crest 24 first.
	var peaked := peak_swag >= THRESHOLD_ENCORE
	# "Engaged" = you actually played the Aura game (posed, finished, or hoarded to the
	# draw line) — as opposed to coasting on passive drip. A long fight (turn>=4) where
	# you never engaged is a flat performance → C, even if you won. Quick wins (turn<4)
	# and any threshold-lit engaged fight stay B. (Context-aware C, pass #2.)
	# Engagement asymmetry by class is intentional: Fire/Necro (drip>0) reach peak>=12
	# passively and stay B in flat fights, while the drip-0 Rizzard must actively pose,
	# finish, or hoard to avoid the flat-fight C — nudging it to engage the Aura economy.
	var engaged := pose_swag > 0 or finisher_clean or peak_swag >= THRESHOLD_DRAW
	var rating := "C"
	if lit >= 3 and finisher_clean and bold and peaked:
		rating = "S"
	elif lit >= 3 or (lit >= 2 and finisher_clean):
		rating = "A"
	elif lit >= 1 and (engaged or turn < 4):
		rating = "B"
	return {
		"rating": rating,
		"peak_swag": peak_swag,
		"thresholds_lit": lit,
		"finisher_clean": finisher_clean,
		"turns": turn,
		"hp_lost": (player.max_hp - player.hp) if player != null else 0,
		"signature": style_signature(),
		"finisher_kind": finisher_kind,
		"booed": booed,
	}

## The fingerprint of HOW this fight was won — the dimension the Critic's taste
## drifts across (P2). A clean cash-out is named by its style (so different
## finishers read as different); otherwise spread vs flex vs hoard vs grind.
func style_signature() -> StringName:
	if finisher_clean and finisher_kind != &"":
		return finisher_kind
	if peak_undead >= 4:
		return &"swarm"          # held a big Goon board (Necro-B), distinct from sac's drain
	if aoe_plays > single_plays and aoe_plays > 0:
		return &"spread"
	if flexed:
		return &"flex"
	if peak_swag >= THRESHOLD_PIERCE:
		return &"hoard"
	return &"grind"

## Just the letter — for the live in-combat readout.
func live_rating() -> String:
	return String(compute_show_rating()["rating"])

func end_turn() -> void:
	if state != State.PLAYER_TURN:
		return
	if pending_pick_n > 0:
		resolve_pick(0)   # a turn can't end mid-pick; the top card is the default
	if retain_hand or has_passive(&"retain_hand_always"):
		retain_hand = false
		_say(Loc.t("you keep the hand — it's all part of the plan"))
	else:
		discard_pile.append_array(hand)
		hand.clear()
	goon_strike()
	if state == State.WIN:
		return
	_decay(player)
	_enemy_turn()

## Who the squad jumps: random by default; wardrobe/relics can teach them to
## pick on the weakest (cleanup kills) or gang up on the biggest threat.
func goon_target() -> Combatant:
	var alive := living_enemies()
	if alive.is_empty():
		return null
	if has_passive(&"goons_target_weakest"):
		var weakest: Combatant = alive[0]
		for e in alive:
			if e.hp < weakest.hp:
				weakest = e
		return weakest
	if has_passive(&"goons_target_strongest"):
		var strongest: Combatant = alive[0]
		for e in alive:
			if e.hp > strongest.hp:
				strongest = e
		return strongest
	return alive[randi() % alive.size()]

## The squad throws hands: end of every turn, or early when a card commands it.
## Critical mass (pass #4): a real mob (4+) hits for 3 each, not 2.
func goon_strike() -> int:
	var undead := player.status(&"undead")
	if undead <= 0 or state != State.PLAYER_TURN:
		return 0
	var tgt := goon_target()
	if tgt == null:
		return 0
	var dmg := undead * (3 if undead >= 4 else 2)
	tgt.take_damage(dmg)
	_say(Loc.t("your %d Goons threw hands for %d") % [undead, dmg])
	goons_attacked.emit(enemies.find(tgt), dmg)
	if all_dead():
		_finish(true)
	_emit()
	return dmg

func _enemy_turn() -> void:
	state = State.ENEMY_TURN
	_emit()
	# snapshot so an ally summoned mid-turn doesn't also act this turn
	for e in enemies.duplicate():
		if e.is_dead():
			continue
		var burned := _tick_burn(e)
		if burned > 0:
			_say(Loc.t("%s got Roasted for %d") % [Loc.t(e.display_name), burned])
		var poisoned := _tick_poison(e)
		if poisoned > 0:
			_say(Loc.t("%s is Toxic'd for %d") % [Loc.t(e.display_name), poisoned])
		if e.is_dead():
			_emit()   # a DoT death gets its own beat before the next enemy moves
			continue
		if e.data == null or e.data.intents.is_empty():
			continue
		if step_delay > 0.0:
			await _beat(step_delay)
			enemy_acting.emit(enemies.find(e), peek_intent(e))
			await _beat(step_delay * 0.4)   # windup: the lunge reads before the hit lands
		var intent: Dictionary = e.data.intents[e.intent_index % e.data.intents.size()]
		_resolve_intent(e, intent)
		e.intent_index += 1
		_decay(e)
		e.block = 0
		# Per-enemy emit: damage numbers, hurt flash, and bar updates land per attacker
		# instead of one aggregated delta at the end of the whole turn.
		_emit()
		if player.is_dead():
			_finish(false)
			return
	if all_dead():
		_finish(true)
		return
	if step_delay > 0.0:
		await _beat(step_delay * 0.8)
	# Block held through the enemy turn (so it absorbed their attacks); clear it now,
	# right before your next turn — StS-correct. (Was wrongly cleared in end_turn, so
	# block never protected against enemies.) set_spray relic keeps up to 6 of it.
	player.block = mini(player.block, 6) if has_passive(&"block_carryover_6") else 0
	_start_player_turn()

func _beat(seconds: float) -> void:
	var tree := Engine.get_main_loop() as SceneTree
	if tree != null:
		await tree.create_timer(seconds).timeout

func _make_enemy(edata: EnemyData) -> Combatant:
	var e := Combatant.new()
	e.display_name = edata.title
	e.data = edata
	e.max_hp = int(round(edata.max_hp * enemy_hp_scale))
	e.hp = e.max_hp
	return e

func _resolve_intent(src: Combatant, intent: Dictionary) -> void:
	var amount := int(intent.get("amount", 0))
	var name := Loc.t(src.display_name)
	match String(intent.get("op", "")):
		"attack":
			var hits: int = max(1, int(intent.get("hits", 1)))
			var dmg := int(round(amount * enemy_dmg_scale))
			var hp0 := player.hp
			for _h in hits:
				# Ghosted (evade): each stack dodges one attack HIT entirely. DoT ticks,
				# status/drain/tax intents are not hits and pass right through.
				if player.status(&"evade") > 0:
					player.add_status(&"evade", -1)
					_say(Loc.t("GHOSTED — you left that hit on read"))
					continue
				player.take_damage(EffectResolver.compute_damage(dmg, src, player))
			if hits > 1:
				_say(Loc.t("%s went off — %d×%d (%d)") % [name, dmg, hits, hp0 - player.hp])
			else:
				_say(Loc.t("%s threw hands for %d") % [name, hp0 - player.hp])
			# took a hit while hoarding above the pierce line → a risky flex (fingerprint)
			if swag >= THRESHOLD_PIERCE and player.hp < hp0:
				flexed = true
			if not src.is_dead() and has_passive(&"thorns_3"):
				src.take_damage(3)
				_say(Loc.t("thorns! %s caught a fade for 3") % name)
		"heal":
			var before := src.hp
			src.heal(amount)
			_say(Loc.t("%s restocked %d HP") % [name, src.hp - before])
		"block":
			src.block += amount
			_say(Loc.t("%s is being unbothered (Block %d)") % [name, amount])
		"apply_status":
			var s := StringName(intent.get("status", &""))
			player.add_status(s, amount)
			_say(Loc.t("%s hit you with %s %d") % [name, _disp(s), amount])
		"buff":
			var s2 := StringName(intent.get("status", &""))
			src.add_status(s2, amount)
			_say(Loc.t("%s locked in: %s +%d") % [name, _disp(s2), amount])
		"drain_swag":
			var before := swag
			swag = max(0, swag - amount)
			_say(Loc.t("%s drained %d of your Aura") % [name, before - swag])
		"tax":
			# Counter-play to hoarding: taxes your Aura only while you sit on a pile.
			var thr := int(intent.get("threshold", THRESHOLD_DRAW))
			if swag >= thr:
				var before2 := swag
				swag = max(0, swag - amount)
				_say(Loc.t("%s taxed your hoard for %d") % [name, before2 - swag])
			else:
				_say(Loc.t("%s wants to tax you but you're broke") % name)
		"summon_ally":
			var sid := StringName(intent.get("enemy", &""))
			var ed := Database.get_enemy(sid)
			# "once": this ally takes the booking a single time per fight — kill it
			# and it STAYS gone (the Talent Agent's clients have other gigs).
			if bool(intent.get("once", false)) and summoned_ids.has(sid):
				_say(Loc.t("%s makes a call... no one picks up.") % name)
			elif ed != null and living_enemies().size() < 4:
				summoned_ids[sid] = true
				enemies.append(_make_enemy(ed))
				_say(Loc.t("%s called backup: %s pulled up!") % [name, Loc.t(ed.title)])
		"steal_gold":
			# The IRS: garnishes a CUT of your purse. Kill it before it flees and
			# the refund comes back at the end of the fight.
			var pct := int(intent.get("percent", 25))
			var take := int(player_gold * pct / 100.0)
			if take > 0:
				player_gold -= take
				src.stolen_gold += take
				_say(Loc.t("%s garnished %d gold. straight to collections.") % [name, take])
			else:
				_say(Loc.t("%s audits you... you're already broke. embarrassing.") % name)
		"flee":
			src.fled = true
			if src.stolen_gold > 0:
				_say(Loc.t("%s files your case and DIPS with %d gold!") % [name, src.stolen_gold])
			else:
				_say(Loc.t("%s files your case and dips.") % name)
		_:
			push_warning("[CombatManager] unknown intent: " + String(intent.get("op", "")))

func peek_intent(e: Combatant) -> Dictionary:
	if e == null or e.data == null or e.data.intents.is_empty():
		return {}
	return e.data.intents[e.intent_index % e.data.intents.size()]

# --- helpers -------------------------------------------------------------

func _total_enemy_hp() -> int:
	var t := 0
	for e in enemies:
		t += e.hp
	return t

func _tick_burn(c: Combatant) -> int:
	var b := c.status(&"burn")
	if b <= 0:
		return 0
	c.take_damage(b, true)
	if b - 1 <= 0:
		c.statuses.erase(&"burn")
	else:
		c.statuses[&"burn"] = b - 1
	return b

# Poison: deal stacks as unblockable damage at the victim's turn start, then ramp down 1.
func _tick_poison(c: Combatant) -> int:
	var p := c.status(&"poison")
	if p <= 0:
		return 0
	c.take_damage(p, true)
	if p - 1 <= 0:
		c.statuses.erase(&"poison")
	else:
		c.statuses[&"poison"] = p - 1
	return p

func _decay(c: Combatant) -> void:
	for s in [&"weak", &"vulnerable", &"jinx", &"frail"]:
		var v := c.status(s)
		if v > 0:
			if v - 1 <= 0:
				c.statuses.erase(s)
			else:
				c.statuses[s] = v - 1

func draw_cards(n: int) -> void:
	_draw(n)

func _draw(n: int) -> void:
	for i in n:
		if hand.size() >= HAND_CAP:
			return
		if draw_pile.is_empty():
			if discard_pile.is_empty():
				return
			draw_pile = discard_pile.duplicate()
			discard_pile.clear()
			draw_pile.shuffle()
		hand.append(draw_pile.pop_back())

## "peek" op: reveal the next n draws. If the draw pile is dry it reshuffles the
## discard in first — exactly what _draw would do — so the peek never lies.
func peek_draw(n: int) -> void:
	if draw_pile.is_empty() and not discard_pile.is_empty():
		recycle_discard()
	var titles: Array = []
	for i in range(mini(n, draw_pile.size())):
		titles.append(draw_pile[draw_pile.size() - 1 - i].title)
	if titles.is_empty():
		_say(Loc.t("nothing left to peek — your piles are empty"))
	else:
		var disp: Array[String] = []
		for t in titles:
			disp.append(Loc.t(t))
		_say(Loc.t("up next: %s") % " · ".join(disp))
	peeked.emit(titles)

## "peek_pick" op: lay out the next n draws and let the player TAKE one. With a
## view attached (step_delay > 0) this emits pick_requested and waits for
## resolve_pick(i); headless it takes the top card immediately — exactly what a
## plain draw would have given, so tests and the balance sim see "draw 1".
func request_pick(n: int) -> void:
	if draw_pile.is_empty() and not discard_pile.is_empty():
		recycle_discard()
	var k: int = mini(n, draw_pile.size())
	if k <= 0:
		_say(Loc.t("nothing left to peek — your piles are empty"))
		return
	pending_pick_n = k
	if step_delay <= 0.0:
		resolve_pick(0)
		return
	var cards: Array = []
	for i in range(k):
		cards.append(draw_pile[draw_pile.size() - 1 - i])
	pick_requested.emit(cards)

## i is the display index (0 = top of pile). Removes that exact position so the
## remaining peeked cards keep their promised order.
func resolve_pick(i: int) -> void:
	if pending_pick_n <= 0:
		return
	var idx: int = draw_pile.size() - 1 - clampi(i, 0, pending_pick_n - 1)
	pending_pick_n = 0
	if idx < 0 or idx >= draw_pile.size():
		return
	if hand.size() >= HAND_CAP:
		_say(Loc.t("your hands are FULL — it stays in the pile"))
		_emit()
		return
	var card: CardData = draw_pile[idx]
	draw_pile.remove_at(idx)
	hand.append(card)
	_say(Loc.t("you reach for %s") % Loc.t(card.title))
	_emit()

## "shuffle_discard" op: the whole discard pile shuffles back into the draw pile.
func recycle_discard() -> void:
	if discard_pile.is_empty():
		return
	draw_pile.append_array(discard_pile)
	discard_pile.clear()
	draw_pile.shuffle()
	_say(Loc.t("fresh rotation — the discard shuffles back in"))

func _log_card(card: CardData, dmg: int, blk: int, burn_added: int, swag_delta: int, pierced: bool) -> void:
	var parts: Array[String] = []
	if dmg > 0:
		parts.append(Loc.t("%d dmg") % dmg)
	if blk > 0:
		parts.append(Loc.t("%d block") % blk)
	if burn_added > 0:
		parts.append(Loc.t("%d burn") % burn_added)
	if swag_delta > 0:
		parts.append("+%d aura" % swag_delta)
	elif swag_delta < 0:
		parts.append(Loc.t("spent %d aura") % -swag_delta)
	if pierced and dmg > 0:
		parts.append(Loc.t("pierced!"))
	var msg := Loc.t("You play %s") % Loc.t(card.title)
	if not parts.is_empty():
		msg += "  ·  " + ", ".join(parts)
	_say(msg)

func _finish(victory: bool) -> void:
	state = State.WIN if victory else State.LOSE
	# Gold-thief settlement: anything a KILLED thief garnished comes back; what a
	# FLED thief took is gone for good.
	if victory:
		var refund := 0
		for e in enemies:
			if e.stolen_gold > 0 and not e.fled:
				refund += e.stolen_gold
				e.stolen_gold = 0
		if refund > 0:
			player_gold += refund
			_say(Loc.t("your refund came through: +%d gold") % refund)
	_say(Loc.t("BIG W!") if victory else Loc.t("you took an L."))
	# Emit the final UI update first (death poofs/popups run while the combat scene
	# is still in the tree), THEN signal the end — which may change scene and detach us.
	_emit()
	combat_ended.emit(victory)

func _disp(s: StringName) -> String:
	return _DISP.get(s, String(s).capitalize())

func _say(msg: String) -> void:
	log_lines.append(msg)
	while log_lines.size() > LOG_KEEP:
		log_lines.pop_front()

func _emit() -> void:
	if player != null:
		peak_undead = max(peak_undead, player.status(&"undead"))
	changed.emit()
