class_name LocES
extends RefCounted
## Spanish translations. Keeps the international Gen-Z slang (Rizz, Aura, Slay,
## Delulu, Sigma, Glow Up, Cooked, Mid, "it's giving"...) and game keywords
## (Goon, Roast/Roasted, Toxic) — translates the connective/narrative text.

const TABLE := {
	# --- menu / chrome ---
	"▶   New Game": "▶   Partida Nueva",
	"↻   Continue": "↻   Continuar",
	"↻   Continue   (✦ %d)": "↻   Continuar   (✦ %d)",
	"⚙   Options": "⚙   Opciones",
	"✕   Exit Game": "✕   Salir",
	"a roguelike deckbuilder about drip": "un roguelike de mazos sobre el drip",
	"F11 toggles fullscreen": "F11 cambia a pantalla completa",
	"← Back to Menu": "← Volver al Menú",
	"← Back": "← Atrás",
	"← Cancel": "← Cancelar",
	"← Menu": "← Menú",
	"Cancel": "Cancelar",
	"Close": "Cerrar",
	"Continue": "Continuar",
	"Confirm Reset?": "¿Confirmar reinicio?",
	"Reset All Progress": "Borrar todo el progreso",
	"Erase & Start Fresh": "Borrar y empezar de cero",
	"This wipes all unlocked clothes and Clout. Click again to confirm.": "Esto borra toda la ropa y el Clout. Haz clic otra vez para confirmar.",
	"Progress reset to a fresh start.": "Progreso reiniciado desde cero.",
	"Starting a new game erases your unlocked clothes and Clout. Continue?": "Una partida nueva borra tu ropa y tu Clout. ¿Continuar?",
	# --- options ---
	"⚙  Options": "⚙  Opciones",
	"Fullscreen:   %s": "Pantalla completa:   %s",
	"Sound FX:   %s": "Efectos:   %s",
	"Music:   %s": "Música:   %s",
	"Language:   %s": "Idioma:   %s",
	"On": "Sí",
	"Off": "No",
	"Attack": "Ataque",
	"Skill": "Habilidad",
	"Power": "Poder",
	# --- class select ---
	"pick your fighter — all your power is in the fit.    ✦ Clout: %d": "elige tu fighter — todo tu poder está en el outfit.    ✦ Clout: %d",
	"the %s": "la/el %s",
	"❤ %d HP": "❤ %d PV",
	"🔒  Unlock at ✦ %d  (you have ✦ %d earned)": "🔒  Desbloquea con ✦ %d  (llevas ✦ %d ganados)",
	"🔥 Ascension 0 / %d  —  base difficulty": "🔥 Ascensión 0 / %d  —  dificultad base",
	"🔥 Ascension %d / %d  —  +%d%% enemy HP, +%d%% dmg, +%d Clout": "🔥 Ascensión %d / %d  —  +%d%% PV enemigos, +%d%% daño, +%d Clout",
	"✦ Boutique  (spend Clout)": "✦ Boutique  (gastar Clout)",
	# --- wizards ---
	"Hot Girl": "Hot Girl",
	"Goth Bestie": "Goth Bestie",
	"Rizzard": "Rizzard",
	"manifests heat, roasts the opps, serves looks for Aura. lowkey a menace 🔥": "manifiesta calor, roastea a los opps, sirve looks por Aura. lowkey un peligro 🔥",
	"summons goons, sacrifices them for clout, steals aura. unbothered & moisturized 💀": "invoca goons, los sacrifica por clout, roba aura. unbothered & moisturized 💀",
	"stacks Rizz to crit harder — pure charisma, zero shame. it's giving unbothered 😎": "acumula Rizz para critear más — puro carisma, cero vergüenza. it's giving unbothered 😎",
	# --- card descriptions ---
	"Deal 5.": "Inflige 5.",
	"Deal 4.": "Inflige 4.",
	"Deal 6.": "Inflige 6.",
	"Gain 9 Block.": "Gana 9 Bloqueo.",
	"Deal 4 to ALL opps.": "Inflige 4 a TODOS.",
	"Deal 2× their Roasted stacks.": "Inflige 2× sus stacks de Roasted.",
	"Gain 5 Block. stay unbothered.": "Gana 5 Bloqueo. sigue unbothered.",
	"Cleanse debuffs. Gain 2 Rizz. delulu is the solulu.": "Limpia debuffs. +2 Rizz. delulu is the solulu.",
	"Deal 4. Heal 3.": "Inflige 4. Cura 3.",
	"Deal 6. it's giving warm 🔥": "Inflige 6. it's giving calorcito 🔥",
	"Deal 5. pew pew 🔫": "Inflige 5. pew pew 🔫",
	"Deal 4. If they're Roasted, deal 4 more.": "Inflige 4. Si están Roasted, 4 más.",
	"Deal 8 to ALL opps. Aura +2.": "Inflige 8 a TODOS. Aura +2.",
	"Gain 2 Rizz. (Rizz = crit chance)": "+2 Rizz. (Rizz = prob. de crítico)",
	"Gain 6 Block. Aura +1.": "Gana 6 Bloqueo. Aura +1.",
	"Finisher. Spend ALL Aura. Deal Aura × 3.": "Finisher. Gasta TODA el Aura. Daño = Aura × 3.",
	"Power: gain 3 Block at the start of every turn. rise and grind.": "Poder: +3 Bloqueo al inicio de cada turno. rise and grind.",
	"Make them Cooked +1. Aura +1.": "Ponlos Cooked +1. Aura +1.",
	"Power: raise 1 Goon at the start of every turn. the squad grows.": "Poder: invoca 1 Goon al inicio de cada turno. la squad crece.",
	"Deal 5. Aura +2.": "Inflige 5. Aura +2.",
	"Roast for 3. Aura +1.": "Roast por 3. Aura +1.",
	"Roast for 5. Aura +2.": "Roast por 5. Aura +2.",
	"Gain 5 Block. gatekeeping my HP": "Gana 5 Bloqueo. gatekeeping mis PV",
	"Deal 6. Gain 2 Rizz. feeling lucky?": "Inflige 6. +2 Rizz. ¿feeling lucky?",
	"Sacrifice a Goon: deal 7, Aura +3.": "Sacrifica un Goon: inflige 7, Aura +3.",
	"Summon 2 Goons. Aura +1.": "Invoca 2 Goons. Aura +1.",
	"Power: gain 1 Rizz at the start of every turn. it just works.": "Poder: +1 Rizz al inicio de cada turno. it just works.",
	"Draw 2 cards.": "Roba 2 cartas.",
	"Summon 1 Goon. Aura +1.": "Invoca 1 Goon. Aura +1.",
	"Gain 3 Rizz. Draw 1.": "+3 Rizz. Roba 1.",
	"Gain 6 Block. Draw 1.": "Gana 6 Bloqueo. Roba 1.",
	"Gain 5 Block.": "Gana 5 Bloqueo.",
	"Power: +1 Aura at the start of every turn. let it cook.": "Poder: +1 Aura al inicio de cada turno. let it cook.",
	"Make them Mid +2. Gain 1 Rizz.": "Ponlos Mid +2. +1 Rizz.",
	"Deal 7. Heal 4.": "Inflige 7. Cura 4.",
	"Apply 4 Toxic. it ramps down each turn but it hurts.": "Aplica 4 Toxic. baja cada turno pero duele.",
	"Aura +3.": "Aura +3.",
	"Cleanse all debuffs. Gain 5 Block. reset your aura fr.": "Limpia todos los debuffs. +5 Bloqueo. resetea tu aura fr.",
	"Aura +2. Gain 3 Block.": "Aura +2. Gana 3 Bloqueo.",
	"Deal 4. Gain 1 Rizz. 😉": "Inflige 4. +1 Rizz. 😉",
	# --- enemies ---
	"Angry Toaster": "Tostadora Furiosa",
	"Cursed Mirror": "Espejo Maldito",
	"Disgruntled Pigeon": "Paloma Cabreada",
	"Feral Houseplant": "Planta Salvaje",
	"Garden Gargoyle": "Gárgola de Jardín",
	"Garden Gnome": "Enano de Jardín",
	"Haunted Umbrella": "Paraguas Embrujado",
	"Possessed Mannequin": "Maniquí Poseído",
	"Possessed Router": "Router Poseído",
	"Possessed Wardrobe": "Armario Poseído",
	"Sock Puppet": "Marioneta de Calcetín",
	"Taxidermy Owl": "Búho Disecado",
	"Unhinged Housecat": "Gato Desquiciado",
	"Vengeful Vending Machine": "Máquina Expendedora Vengativa",
	"Wi-Fi Gremlin": "Gremlin del Wi-Fi",
	"Gym Rat": "Gym Rat",
	"Hater in the Replies": "Hater en los Replies",
	# --- artifacts ---
	"Bone Charm": "Amuleto de Hueso",
	"Designer Purse": "Bolso de Diseño",
	"Ember Pin": "Broche de Brasa",
	"Ring of Excess": "Anillo del Exceso",
	"Glitter Brooch": "Broche de Purpurina",
	"Iron Corset": "Corsé de Hierro",
	"Loaded Dice": "Dados Trucados",
	"Phoenix Feather": "Pluma de Fénix",
	"Cat-Eye Glasses": "Gafas Cat-Eye",
	"Spotlight": "Foco",
	"Fog Machine": "Máquina de Humo",
	"Vampire Fang": "Colmillo de Vampiro",
	"Venom Vial": "Vial de Veneno",
	"Gym Membership": "Abono del Gym",
	"Summons summon +1 Goon.": "Las invocaciones invocan +1 Goon.",
	"Gain 8 gold after each combat.": "+8 oro tras cada combate.",
	"Your Roast applies +1 stack.": "Tu Roast aplica +1 stack.",
	"+1 Energy each turn.": "+1 Energía por turno.",
	"Aura cards grant +1 Aura.": "Las cartas de Aura dan +1 Aura.",
	"When an enemy hits you, deal 3 back.": "Cuando te golpean, devuelve 3.",
	"Your attacks crit 15% of the time (x2 damage).": "Tus ataques critean el 15% (x2 daño).",
	"Your first spell each turn deals +3.": "Tu primer hechizo del turno hace +3.",
	"Draw +1 card each turn.": "Roba +1 carta por turno.",
	"Every enemy starts combat Cooked (Vulnerable 1).": "Cada enemigo empieza Cooked (Vulnerable 1).",
	"+2 Aura income each turn.": "+2 de Aura por turno.",
	"Heal 3 at the start of each turn.": "Cura 3 al inicio de cada turno.",
	"Toxic you apply gets +1 stack.": "El Toxic que aplicas: +1 stack.",
	"Start each combat with 2 Rizz.": "Empieza cada combate con 2 Rizz.",
	# --- outfits ---
	"Apprentice Hat": "Sombrero de Aprendiz",
	"Bone Scepter": "Cetro de Hueso",
	"Catwalk Heels": "Tacones de Pasarela",
	"Char Wand": "Varita de Carbón",
	"Hype Charm": "Amuleto Hype",
	"Diva Heels": "Tacones de Diva",
	"Drip Robe": "Túnica de Drip",
	"Influencer Ring": "Anillo de Influencer",
	"Lucky Cap": "Gorra de la Suerte",
	"Lucky Charm": "Amuleto de la Suerte",
	"Phoenix Gown": "Túnica de Fénix",
	"Plain Wand": "Varita Simple",
	"Swag Cap": "Gorra Swag",
	"Robe of Excess": "Túnica del Exceso",
	"Showstopper Hat": "Sombrero Showstopper",
	"Smolder Boots": "Botas de Brasa",
	"Worn Boots": "Botas Gastadas",
	"At 12+ Aura: +1 Rizz/turn.": "Con 12+ Aura: +1 Rizz/turno.",
	"Start combat with 5 Block.": "Empieza con 5 Bloqueo.",
	"Hit back for 3 when struck.": "Devuelve 3 al ser golpeado.",
	"Attacks crit 10% of the time.": "Los ataques critean el 10%.",
	"Heal 3 each turn.": "Cura 3 por turno.",
	"Start combat with 3 Aura.": "Empieza con 3 Aura.",
	"First spell each turn: +3 dmg.": "Primer hechizo del turno: +3 daño.",
	# --- wardrobe / boutique ---
	"Hat": "Sombrero",
	"Robe": "Túnica",
	"Staff": "Bastón",
	"Boots": "Botas",
	"Trinket": "Amuleto",
	"OWNED": "EN POSESIÓN",
	"%s, the %s    —    pick your drip": "%s, la/el %s    —    elige tu drip",
	"Spend Clout on permanent drip. You have ✦ %d Clout.": "Gasta Clout en drip permanente. Tienes ✦ %d Clout.",
	"THE FIT": "EL OUTFIT",
	"✦ Aura income: +%d / turn": "✦ Ingreso de Aura: +%d / turno",
	"🃏 Cards added to deck: %d": "🃏 Cartas añadidas: %d",
	"drip perks:": "perks de drip:",
	"  (none)": "  (ninguno)",
	"(nothing owned)": "(nada en posesión)",
	"let's get it →": "¡vamos! →",
	# --- combat HUD ---
	"THEIR TURN": "TURNO RIVAL",
	"TURN %d": "TURNO %d",
	"⚡ Energy  %d / %d": "⚡ Energía  %d / %d",
	"✦ AURA  %d   (+%d/turn)": "✦ AURA  %d   (+%d/turno)",
	"%s ≥6 +2dmg    %s ≥12 +draw    %s ≥18 pierce": "%s ≥6 +2daño    %s ≥12 +carta    %s ≥18 Pierce",
	"Bye ✌": "Chao ✌",
}
