class_name LocDE
extends RefCounted
## German translations. Keeps the international Gen-Z slang (Rizz, Aura, Slay,
## Delulu, Sigma, Glow Up, Cooked, Mid, "it's giving"...) and the game keywords
## (Block, Goon, Roast/Roasted, Toxic) — translates the connective/narrative text.

const TABLE := {
	# --- menu / chrome ---
	"▶   New Game": "▶   Neues Spiel",
	"↻   Continue": "↻   Weiter",
	"↻   Continue   (✦ %d)": "↻   Weiter   (✦ %d)",
	"⚙   Options": "⚙   Optionen",
	"✕   Exit Game": "✕   Beenden",
	"a roguelike deckbuilder about drip": "ein Roguelike-Deckbuilder über Drip",
	"F11 toggles fullscreen": "F11 schaltet Vollbild um",
	"← Back to Menu": "← Zurück zum Menü",
	"← Back": "← Zurück",
	"← Cancel": "← Abbrechen",
	"← Menu": "← Menü",
	"Cancel": "Abbrechen",
	"Close": "Schließen",
	"Continue": "Weiter",
	"Confirm Reset?": "Zurücksetzen bestätigen?",
	"Reset All Progress": "Fortschritt löschen",
	"Erase & Start Fresh": "Löschen & neu starten",
	"This wipes all unlocked clothes and Clout. Click again to confirm.": "Das löscht alle Klamotten und Clout. Nochmal klicken zum Bestätigen.",
	"Progress reset to a fresh start.": "Fortschritt auf Anfang zurückgesetzt.",
	"Starting a new game erases your unlocked clothes and Clout. Continue?": "Ein neues Spiel löscht deine Klamotten und Clout. Weiter?",
	# --- options ---
	"⚙  Options": "⚙  Optionen",
	"Fullscreen:   %s": "Vollbild:   %s",
	"Sound FX:   %s": "Soundeffekte:   %s",
	"Music:   %s": "Musik:   %s",
	"Language:   %s": "Sprache:   %s",
	"On": "An",
	"Off": "Aus",
	"Attack": "Angriff",
	"Skill": "Skill",
	"Power": "Kraft",
	"Deutsch": "Deutsch",
	"English": "English",
	"Español": "Español",
	# --- class select ---
	"pick your fighter — all your power is in the fit.    ✦ Clout: %d": "wähl deinen Fighter — deine ganze Power steckt im Fit.    ✦ Clout: %d",
	"the %s": "der/die %s",
	"❤ %d HP": "❤ %d LP",
	"🔒  Unlock at ✦ %d  (you have ✦ %d earned)": "🔒  Freischalten bei ✦ %d  (du hast ✦ %d verdient)",
	"🔥 Ascension 0 / %d  —  base difficulty": "🔥 Ascension 0 / %d  —  Basis-Schwierigkeit",
	"🔥 Ascension %d / %d  —  +%d%% enemy HP, +%d%% dmg, +%d Clout": "🔥 Ascension %d / %d  —  +%d%% Gegner-LP, +%d%% Schaden, +%d Clout",
	"✦ Boutique  (spend Clout)": "✦ Boutique  (Clout ausgeben)",
	# --- wizards ---
	"Hot Girl": "Hot Girl",
	"Goth Bestie": "Goth Bestie",
	"Rizzard": "Rizzard",
	"manifests heat, roasts the opps, serves looks for Aura. lowkey a menace 🔥": "manifestiert Hitze, roastet die Opps, serviert Looks für Aura. lowkey eine Gefahr 🔥",
	"summons goons, sacrifices them for clout, steals aura. unbothered & moisturized 💀": "beschwört Goons, opfert sie für Clout, klaut Aura. unbothered & moisturized 💀",
	"stacks Rizz to crit harder — pure charisma, zero shame. it's giving unbothered 😎": "stackt Rizz für härtere Crits — pures Charisma, null Scham. it's giving unbothered 😎",
	# --- card descriptions (slang titles kept; connective text translated) ---
	"Deal 5.": "5 Schaden.",
	"Deal 4.": "4 Schaden.",
	"Deal 6.": "6 Schaden.",
	"Gain 9 Block.": "Erhalte 9 Block.",
	"Deal 4 to ALL opps.": "4 Schaden an ALLE Opps.",
	"Deal 2× their Roasted stacks.": "2× ihre Roasted-Stacks Schaden.",
	"Gain 5 Block. stay unbothered.": "Erhalte 5 Block. bleib unbothered.",
	"Cleanse debuffs. Gain 2 Rizz. delulu is the solulu.": "Reinige Debuffs. +2 Rizz. delulu is the solulu.",
	"Deal 4. Heal 3.": "4 Schaden. Heile 3.",
	"Deal 6. it's giving warm 🔥": "6 Schaden. it's giving warm 🔥",
	"Deal 5. pew pew 🔫": "5 Schaden. pew pew 🔫",
	"Deal 4. If they're Roasted, deal 4 more.": "4 Schaden. Wenn Roasted, 4 extra.",
	"Deal 8 to ALL opps. Aura +2.": "8 Schaden an ALLE Opps. Aura +2.",
	"Gain 2 Rizz. (Rizz = crit chance)": "+2 Rizz. (Rizz = Crit-Chance)",
	"Gain 6 Block. Aura +1.": "Erhalte 6 Block. Aura +1.",
	"Finisher. Spend ALL Aura. Deal Aura × 3.": "Finisher. Verbrauch ALLE Aura. Schaden = Aura × 3.",
	"Power: gain 3 Block at the start of every turn. rise and grind.": "Kraft: +3 Block zu Beginn jedes Zuges. rise and grind.",
	"Make them Cooked +1. Aura +1.": "Mach sie Cooked +1. Aura +1.",
	"Power: raise 1 Goon at the start of every turn. the squad grows.": "Kraft: beschwör 1 Goon zu Beginn jedes Zuges. die Squad wächst.",
	"Deal 5. Aura +2.": "5 Schaden. Aura +2.",
	"Roast for 3. Aura +1.": "Roast für 3. Aura +1.",
	"Roast for 5. Aura +2.": "Roast für 5. Aura +2.",
	"Gain 5 Block. gatekeeping my HP": "Erhalte 5 Block. gatekeeping my LP",
	"Deal 6. Gain 2 Rizz. feeling lucky?": "6 Schaden. +2 Rizz. feeling lucky?",
	"Sacrifice a Goon: deal 7, Aura +3.": "Opfer einen Goon: 7 Schaden, Aura +3.",
	"Summon 2 Goons. Aura +1.": "Beschwör 2 Goons. Aura +1.",
	"Power: gain 1 Rizz at the start of every turn. it just works.": "Kraft: +1 Rizz zu Beginn jedes Zuges. it just works.",
	"Draw 2 cards.": "Zieh 2 Karten.",
	"Summon 1 Goon. Aura +1.": "Beschwör 1 Goon. Aura +1.",
	"Gain 3 Rizz. Draw 1.": "+3 Rizz. Zieh 1.",
	"Gain 6 Block. Draw 1.": "Erhalte 6 Block. Zieh 1.",
	"Gain 5 Block.": "Erhalte 5 Block.",
	"Power: +1 Aura at the start of every turn. let it cook.": "Kraft: +1 Aura zu Beginn jedes Zuges. let it cook.",
	"Make them Mid +2. Gain 1 Rizz.": "Mach sie Mid +2. +1 Rizz.",
	"Deal 7. Heal 4.": "7 Schaden. Heile 4.",
	"Apply 4 Toxic. it ramps down each turn but it hurts.": "Gib 4 Toxic. sinkt jeden Zug, tut aber weh.",
	"Aura +3.": "Aura +3.",
	"Cleanse all debuffs. Gain 5 Block. reset your aura fr.": "Reinige alle Debuffs. +5 Block. reset deine Aura fr.",
	"Aura +2. Gain 3 Block.": "Aura +2. Erhalte 3 Block.",
	"Deal 4. Gain 1 Rizz. 😉": "4 Schaden. +1 Rizz. 😉",
	# --- enemies (plain names translated; meme/slang names kept) ---
	"Angry Toaster": "Wütender Toaster",
	"Cursed Mirror": "Verfluchter Spiegel",
	"Disgruntled Pigeon": "Mürrische Taube",
	"Feral Houseplant": "Wilde Zimmerpflanze",
	"Garden Gargoyle": "Garten-Gargoyle",
	"Garden Gnome": "Gartenzwerg",
	"Haunted Umbrella": "Spuk-Regenschirm",
	"Possessed Mannequin": "Besessene Schaufensterpuppe",
	"Possessed Router": "Besessener Router",
	"Possessed Wardrobe": "Besessener Kleiderschrank",
	"Sock Puppet": "Sockenpuppe",
	"Taxidermy Owl": "Ausgestopfte Eule",
	"Unhinged Housecat": "Durchgedrehte Hauskatze",
	"Vengeful Vending Machine": "Rachsüchtiger Automat",
	"Wi-Fi Gremlin": "WLAN-Gremlin",
	"Gym Rat": "Gym Rat",
	"Hater in the Replies": "Hater in den Replies",
	# --- artifacts ---
	"Bone Charm": "Knochen-Anhänger",
	"Designer Purse": "Designer-Handtasche",
	"Ember Pin": "Glut-Anstecker",
	"Ring of Excess": "Ring des Exzess",
	"Glitter Brooch": "Glitzer-Brosche",
	"Iron Corset": "Eisernes Korsett",
	"Loaded Dice": "Gezinkte Würfel",
	"Phoenix Feather": "Phönixfeder",
	"Cat-Eye Glasses": "Cat-Eye-Brille",
	"Spotlight": "Spotlight",
	"Fog Machine": "Nebelmaschine",
	"Vampire Fang": "Vampirzahn",
	"Venom Vial": "Gift-Fläschchen",
	"Gym Membership": "Fitness-Abo",
	"Summons summon +1 Goon.": "Beschwörungen beschwören +1 Goon.",
	"Gain 8 gold after each combat.": "+8 Gold nach jedem Kampf.",
	"Your Roast applies +1 stack.": "Dein Roast gibt +1 Stack.",
	"+1 Energy each turn.": "+1 Energie pro Zug.",
	"Aura cards grant +1 Aura.": "Aura-Karten geben +1 Aura.",
	"When an enemy hits you, deal 3 back.": "Wenn ein Gegner dich trifft, 3 zurück.",
	"Your attacks crit 15% of the time (x2 damage).": "Deine Angriffe critten zu 15% (x2 Schaden).",
	"Your first spell each turn deals +3.": "Dein erster Zauber pro Zug macht +3.",
	"Draw +1 card each turn.": "Zieh +1 Karte pro Zug.",
	"Every enemy starts combat Cooked (Vulnerable 1).": "Jeder Gegner startet Cooked (Vulnerable 1).",
	"+2 Aura income each turn.": "+2 Aura-Einkommen pro Zug.",
	"Heal 3 at the start of each turn.": "Heile 3 zu Beginn jedes Zuges.",
	"Toxic you apply gets +1 stack.": "Toxic, das du gibst, +1 Stack.",
	"Start each combat with 2 Rizz.": "Starte jeden Kampf mit 2 Rizz.",
	# --- outfits ---
	"Apprentice Hat": "Lehrlingshut",
	"Bone Scepter": "Knochenzepter",
	"Catwalk Heels": "Catwalk-Heels",
	"Char Wand": "Kohle-Zauberstab",
	"Hype Charm": "Hype-Anhänger",
	"Diva Heels": "Diva-Heels",
	"Drip Robe": "Drip-Robe",
	"Influencer Ring": "Influencer-Ring",
	"Lucky Cap": "Glücks-Cap",
	"Lucky Charm": "Glücksbringer",
	"Phoenix Gown": "Phönix-Robe",
	"Plain Wand": "Schlichter Stab",
	"Swag Cap": "Swag-Cap",
	"Robe of Excess": "Robe des Exzess",
	"Showstopper Hat": "Showstopper-Hut",
	"Smolder Boots": "Glut-Stiefel",
	"Worn Boots": "Abgetragene Stiefel",
	"At 12+ Aura: +1 Rizz/turn.": "Bei 12+ Aura: +1 Rizz/Zug.",
	"Start combat with 5 Block.": "Starte mit 5 Block.",
	"Hit back for 3 when struck.": "Schlag mit 3 zurück.",
	"Attacks crit 10% of the time.": "Angriffe critten zu 10%.",
	"Heal 3 each turn.": "Heile 3 pro Zug.",
	"Start combat with 3 Aura.": "Starte mit 3 Aura.",
	"First spell each turn: +3 dmg.": "Erster Zauber pro Zug: +3 Schaden.",
	# --- wardrobe / boutique ---
	"Hat": "Hut",
	"Robe": "Robe",
	"Staff": "Stab",
	"Boots": "Stiefel",
	"Trinket": "Schmuck",
	"OWNED": "BESITZT",
	"%s, the %s    —    pick your drip": "%s, der/die %s    —    wähl dein Drip",
	"Spend Clout on permanent drip. You have ✦ %d Clout.": "Gib Clout für permanentes Drip aus. Du hast ✦ %d Clout.",
	"THE FIT": "DAS FIT",
	"✦ Aura income: +%d / turn": "✦ Aura-Einkommen: +%d / Zug",
	"🃏 Cards added to deck: %d": "🃏 Karten im Deck: %d",
	"drip perks:": "Drip-Perks:",
	"  (none)": "  (keine)",
	"(nothing owned)": "(nichts vorhanden)",
	"let's get it →": "los geht's →",
	# --- combat HUD ---
	"THEIR TURN": "GEGNER AM ZUG",
	"TURN %d": "ZUG %d",
	"⚡ Energy  %d / %d": "⚡ Energie  %d / %d",
	"✦ AURA  %d   (+%d/turn)": "✦ AURA  %d   (+%d/Zug)",
	"%s ≥6 +2dmg    %s ≥12 +draw    %s ≥18 pierce": "%s ≥6 +2Schaden    %s ≥12 +Karte    %s ≥18 Pierce",
	"Bye ✌": "Tschö ✌",
	# --- node screens (event / rest / shop / chest / reward choices) ---
	"Cop one (20g)": "Kauf eine (20g)",
	"Dig through it": "Durchwühlen",
	"dip ✌": "abhauen ✌",
	"Do the work": "Mach die Arbeit",
	"Get Snatched": "Lass dich snatchen",
	"Hard pass": "Hartes Nein",
	"I'm fine actually": "Mir geht's gut, echt",
	"Keep it pushing": "Weiterziehen",
	"Log Off": "Log Off",
	"Nope, weird": "Nope, creepy",
	"Not worth it": "Nicht der Rede wert",
	"Pay in vitality": "Mit Vitalität zahlen",
	"Take a sip": "Nimm 'nen Schluck",
	"Toss 15g, make a wish": "15g rein, was wünschen",
	"Try the fit on": "Fit anprobieren",
	"yeet a card (%dg)": "yeet eine Karte (%dg)",
	# --- combat log lines (slang/keywords kept; connective text translated) ---
	"the opps pulled up: %s": "die Opps sind aufgetaucht: %s",
	"you're Toxic'd for %d": "du bist Toxic'd für %d",
	"— Your turn %d  (+%d aura → %d) —": "— Dein Zug %d  (+%d Aura → %d) —",
	"— Your turn %d —": "— Dein Zug %d —",
	"the squad multiplies: +%d Goon": "die Squad wächst: +%d Goon",
	"%s is ENRAGED → +%d Rizz": "%s ist ENRAGED → +%d Rizz",
	"✦ CRIT! that's lethal rizz ✦": "✦ CRIT! das ist lethal Rizz ✦",
	"your %d Goons threw hands for %d": "deine %d Goons haben zugeschlagen für %d",
	"%s got Roasted for %d": "%s wurde Roasted für %d",
	"%s is Toxic'd for %d": "%s ist Toxic'd für %d",
	"%s went off — %d×%d (%d)": "%s ist abgegangen — %d×%d (%d)",
	"%s threw hands for %d": "%s hat zugeschlagen für %d",
	"thorns! %s caught a fade for 3": "Dornen! %s kassiert 3",
	"%s restocked %d HP": "%s füllt %d LP auf",
	"%s is being unbothered (Block %d)": "%s bleibt unbothered (Block %d)",
	"%s hit you with %s %d": "%s trifft dich mit %s %d",
	"%s locked in: %s +%d": "%s locked in: %s +%d",
	"%s drained %d of your Aura 😤": "%s klaut %d deiner Aura 😤",
	"%s called backup: %s pulled up!": "%s ruft Backup: %s ist da!",
	"you took an L 💀": "du kassierst ein L 💀",
	"You play %s": "Du spielst %s",
	"%d dmg": "%d Schaden",
	"%d block": "%d Block",
	"%d burn": "%d Burn",
	"spent %d aura": "%d Aura ausgegeben",
	"pierced!": "pierced!",
	"CRIT!": "CRIT!",
	# --- banter (speech bubbles) — translatable lines; pure slang passes through ---
	"aura farming fr 🧿": "aura farmen fr 🧿",
	"I'm so BACK": "ich bin so BACK",
	"the aura is auraing": "die Aura auraet",
	"we mogging rn 😤": "wir moggen grad 😤",
	"you're so cooked": "du bist so cooked",
	"couldn't be me": "wär mir nie passiert",
	"you fell off": "du bist abgestürzt",
	"0 aura detected": "0 Aura erkannt",
	"stay mad bestie": "bleib mad bestie",
	"ngl your drip is mid": "ngl dein Drip ist mid",
	"bestie you ATE that 💅": "bestie du hast das GESERVED 💅",
	"let me cook 🔥": "lass mich kochen 🔥",
	"touch grass? in THIS economy??": "touch grass? in DIESER Wirtschaft??",
	"no thoughts just drip": "keine Gedanken nur Drip",
	"we stan a serve": "wir stannen einen Serve",
	"sheeeesh that's hard 😤": "sheeeesh das ist hard 😤",
	# --- The Critic (USP) ---
	"+2DMG": "+2 SCH",
	"DRAW": "ZIEHEN",
	"PIERCE": "DURCHBRUCH",
	"✦ FINALE ✦": "✦ FINALE ✦",
	"👀 THE CRITIC:  %s": "👀 DIE KRITIKERIN:  %s",
	"THE CRITIC  %s": "DIE KRITIKERIN  %s",
	"👀 THE CRITIC:  ": "👀 DIE KRITIKERIN:  ",
	"The Critic": "Die Kritikerin",
	"Heckler": "Zwischenrufer",
	"→ a VIP room opens ahead. 👑": "→ ein VIP-Raum öffnet sich. 👑",
	"→ a heckler's waiting in your next fight. 🗣": "→ ein Zwischenrufer wartet im nächsten Kampf. 🗣",
	"S — serve. obsessed. devastating. 💅": "S — serve. besessen. vernichtend. 💅",
	"S — the giiirls are SERVING. iconic.": "S — die giiirls SERVEN. ikonisch.",
	"A — ate. left a crumb on the plate.": "A — ate. ein Krümel blieb auf dem Teller.",
	"A — a real look. almost made me clap.": "A — ein echter Look. fast hätte ich geklatscht.",
	"B — mid showing, bestie. do better.": "B — mid Auftritt, bestie. streng dich an.",
	"B — it was giving... fine. i guess.": "B — it was giving... okay. schätze ich.",
	"C — flop era. who told you that was giving?": "C — flop era. wer hat gesagt das wäre giving?",
	"C — boo. i've seen NPCs with more drip.": "C — buh. ich kenne NPCs mit mehr Drip.",
	# --- Phases 2-4: drift / encore / tax / trend ---
	"S — i felt that in my SOUL. headliner.": "S — das hab ich in der SEELE gespürt. Headliner.",
	"A — so close to perfect it's annoying.": "A — so nah an perfekt, das nervt.",
	"B — i've seen worse. i've seen way better.": "B — schon Schlimmeres gesehen. auch viel Besseres.",
	"C — that wasn't a fit, that was a cry for help.": "C — das war kein Fit, das war ein Hilferuf.",
	"again? 🥱 serve me something NEW.": "schon wieder? 🥱 servier mir was NEUES.",
	"🎤 ENCORE ×%d — the crowd wants MORE": "🎤 ENCORE ×%d — der Saal will MEHR",
	"📉 BOOED OFF — you fell out of the spotlight (−%d Aura)": "📉 AUSGEBUHT — du bist aus dem Rampenlicht gefallen (−%d Aura)",
	"🎤 ENCORE ×%d!": "🎤 ENCORE ×%d!",
	"BOOED 📉": "AUSGEBUHT 📉",
	"%s taxed your hoard for %d 💸": "%s hat deinen Hort um %d besteuert 💸",
	"%s wants to tax you but you're broke 💀": "%s will dich besteuern, aber du bist pleite 💀",
	"📈 TREND: it's giving abundance  (+1 Aura/turn)": "📈 TREND: it's giving Überfluss  (+1 Aura/Zug)",
	"📉 TREND: flop era  (−1 Aura/turn)": "📉 TREND: flop era  (−1 Aura/Zug)",
	"🔥 TREND: going viral  (+1 Aura/turn)": "🔥 TREND: geht viral  (+1 Aura/Zug)",
	"Finisher. Spend ALL Aura. Deal Aura × (2 + Encore). The longer you held the spotlight, the bigger the bow.": "Finisher. Verbrauche ALLE Aura. Mach Aura × (2 + Encore). Je länger du im Rampenlicht standest, desto größer die Verbeugung.",
	"Finisher. Spend ALL Aura. Deal Aura × 1.5 to ALL enemies.": "Finisher. Verbrauche ALLE Aura. Mach Aura × 1,5 an ALLE Gegner.",
	"Finisher. Spend ALL Aura. Deal Aura × 2 to one enemy and heal half the damage.": "Finisher. Verbrauche ALLE Aura. Mach Aura × 2 an einen Gegner und heile die Hälfte des Schadens.",
	"Finishers deal +50%. Low drip — you live for the cash-out, not the slow build.": "Finisher machen +50%. Wenig Drip — du lebst für den Cash-out, nicht den langsamen Aufbau.",
	"High drip: a fat, steady Aura income. Live in the thresholds; hoard, don't dump.": "Viel Drip: ein fettes, stetiges Aura-Einkommen. Lebe in den Schwellen; horte, dump nicht.",
}
