class_name LocES
extends RefCounted
## Spanish translations. Keeps the international Gen-Z slang (Rizz, Aura, Slay,
## Delulu, Sigma, Glow Up, Cooked, Mid, "it's giving"...) and game keywords
## (Goon, Roast/Roasted, Toxic) — translates the connective/narrative text.

const TABLE := {
	# --- menu / chrome ---
	"New Game": "Partida Nueva",
	"Continue": "Continuar",
	"Continue   (%d Clout)": "Continuar   (%d Clout)",
	"Options": "Opciones",
	"Exit Game": "Salir",
	"a roguelike deckbuilder about drip": "un roguelike de mazos sobre el drip",
	"F11 toggles fullscreen": "F11 cambia a pantalla completa",
	"Back to Menu": "Volver al Menú",
	"Back": "Atrás",
	"Cancel": "Cancelar",
	"Menu": "Menú",
	"Close": "Cerrar",
	"Confirm Reset?": "¿Confirmar reinicio?",
	"Reset All Progress": "Borrar todo el progreso",
	"Erase & Start Fresh": "Borrar y empezar de cero",
	"This wipes all unlocked clothes and Clout. Click again to confirm.": "Esto borra toda la ropa y el Clout. Haz clic otra vez para confirmar.",
	"Progress reset to a fresh start.": "Progreso reiniciado desde cero.",
	"Starting a new game erases your unlocked clothes and Clout. Continue?": "Una partida nueva borra tu ropa y tu Clout. ¿Continuar?",
	# --- options ---
	"Fullscreen:   %s": "Pantalla completa:   %s",
	"Sound FX:   %s": "Efectos:   %s",
	"Music:   %s": "Música:   %s",
	"Language:   %s": "Idioma:   %s",
	"On": "Sí",
	"Off": "No",
	"Attack": "Ataque",
	"Skill": "Habilidad",
	"Power": "Poder",
	# --- class select ---
	"pick your fighter — all your power is in the fit.    Clout to spend: %d": "elige tu fighter — todo tu poder está en el outfit.    Clout para gastar: %d",
	"the %s": "la/el %s",
	"%d HP": "%d PV",
	"Locked — unlock at %d Clout  (you have %d earned)": "Bloqueado — desbloquea con %d Clout  (llevas %d ganados)",
	"Ascension 0 / %d  —  base difficulty": "Ascensión 0 / %d  —  dificultad base",
	"Ascension %d / %d  —  +%d%% enemy HP, +%d%% dmg, +%d Clout": "Ascensión %d / %d  —  +%d%% PV enemigos, +%d%% daño, +%d Clout",
	"Boutique  (spend Clout)": "Boutique  (gastar Clout)",
	# --- wizards ---
	"It Girl": "It Girl",
	"Goth Bestie": "Goth Bestie",
	"Rizzard": "Rizzard",
	"manifests heat, roasts the opps, serves looks for Aura. lowkey a menace": "manifiesta calor, roastea a los opps, sirve looks por Aura. lowkey un peligro",
	"summons goons, sacrifices them for clout, steals aura. unbothered & moisturized": "invoca goons, los sacrifica por clout, roba aura. unbothered & moisturized",
	"stacks Rizz to crit harder — pure charisma, zero shame. it's giving unbothered": "acumula Rizz para critear más — puro carisma, cero vergüenza. it's giving unbothered",
	# --- card descriptions ---
	"Deal 5.": "Inflige 5.",
	"Deal 4.": "Inflige 4.",
	"Deal 6.": "Inflige 6.",
	"Gain 9 Block.": "Gana 9 Bloqueo.",
	"Deal 4 to ALL opps.": "Inflige 4 a TODOS.",
	"Deal 2× their Roasted stacks.": "Inflige 2× sus stacks de Roasted.",
	"Gain 5 Block. stay unbothered.": "Gana 5 Bloqueo. sigue unbothered.",
	"Cleanse debuffs. Gain 2 Rizz. delulu is the solulu.": "Limpia debuffs. +2 Rizz. delulu is the solulu.",
	"Deal 4. Heal 3.": "Inflige 4. Cura 3.",
	"Deal 6. it's giving warm": "Inflige 6. it's giving calorcito",
	"Deal 5. pew pew": "Inflige 5. pew pew",
	"Deal 4. If they're Roasted, deal 4 more.": "Inflige 4. Si están Roasted, 4 más.",
	"Deal 8 to ALL opps. Aura +2.": "Inflige 8 a TODOS. Aura +2.",
	"Gain 2 Rizz. (Rizz = crit chance)": "+2 Rizz. (Rizz = prob. de crítico)",
	"Gain 6 Block. Aura +1.": "Gana 6 Bloqueo. Aura +1.",
	"Finisher. Spend ALL Aura. Deal Aura × 3.": "Finisher. Gasta TODA el Aura. Daño = Aura × 3.",
	"Power: gain 3 Block at the start of every turn. rise and grind.": "Poder: +3 Bloqueo al inicio de cada turno. rise and grind.",
	"Make them Cooked +1. Aura +1.": "Ponlos Cooked +1. Aura +1.",
	"Power: raise 1 Goon at the start of every turn. the squad grows.": "Poder: invoca 1 Goon al inicio de cada turno. la squad crece.",
	"Deal 5. Aura +2.": "Inflige 5. Aura +2.",
	"Roast for 4. Aura +1.": "Roast por 4. Aura +1.",
	"Roast for 5. Aura +2.": "Roast por 5. Aura +2.",
	"Gain 5 Block. gatekeeping my HP": "Gana 5 Bloqueo. gatekeeping mis PV",
	"Deal 6. Gain 2 Rizz. feeling lucky?": "Inflige 6. +2 Rizz. ¿feeling lucky?",
	"Sacrifice a Goon: deal 7, Aura +3.": "Sacrifica un Goon: inflige 7, Aura +3.",
	"Summon 2 Goons. Aura +1.": "Invoca 2 Goons. Aura +1.",
	"Power: gain 1 Rizz at the start of every turn. it just works.": "Poder: +1 Rizz al inicio de cada turno. it just works.",
	"Draw 2 cards.": "Roba 2 cartas.",
	"Summon 1 Goon. Aura +1.": "Invoca 1 Goon. Aura +1.",
	"Gain 3 Rizz. Draw 1.": "+3 Rizz. Roba 1.",
	"Gain 6 Block. Draw 1.": "Gana 6 Bloqueo. Roba 1.",
	"Gain 5 Block.": "Gana 5 Bloqueo.",
	"Power: +2 Aura at the start of every turn. let it cook.": "Poder: +2 Aura al inicio de cada turno. let it cook.",
	"Make them Mid +2. Gain 1 Rizz.": "Ponlos Mid +2. +1 Rizz.",
	"Deal 7. Heal 4.": "Inflige 7. Cura 4.",
	"Apply 4 Toxic. it ramps down each turn but it hurts.": "Aplica 4 Toxic. baja cada turno pero duele.",
	"Aura +3.": "Aura +3.",
	"Cleanse all debuffs. Gain 5 Block. reset your aura fr.": "Limpia todos los debuffs. +5 Bloqueo. resetea tu aura fr.",
	"Aura +2. Gain 3 Block.": "Aura +2. Gana 3 Bloqueo.",
	"Deal 4. Gain 1 Rizz.": "Inflige 4. +1 Rizz.",
	# --- enemies ---
	"Angry Toaster": "Tostadora Furiosa",
	"Cursed Mirror": "Espejo Maldito",
	"Disgruntled Pigeon": "Paloma Cabreada",
	"Feral Houseplant": "Planta Salvaje",
	"Garden Gargoyle": "Gárgola de Jardín",
	"Garden Gnome": "Enano de Jardín",
	"Haunted Umbrella": "Paraguas Embrujado",
	"Possessed Mannequin": "Maniquí Poseído",
	"Possessed Router": "Router Poseído",
	"Possessed Wardrobe": "Armario Poseído",
	"Sock Puppet": "Marioneta de Calcetín",
	"Taxidermy Owl": "Búho Disecado",
	"Unhinged Housecat": "Gato Desquiciado",
	"Vengeful Vending Machine": "Máquina Expendedora Vengativa",
	"Wi-Fi Gremlin": "Gremlin del Wi-Fi",
	"Gym Rat": "Gym Rat",
	"Hater in the Replies": "Hater en los Replies",
	# --- artifacts ---
	"Bone Charm": "Amuleto de Hueso",
	"Designer Purse": "Bolso de Diseño",
	"Ember Pin": "Broche de Brasa",
	"Ring of Excess": "Anillo del Exceso",
	"Glitter Brooch": "Broche de Purpurina",
	"Iron Corset": "Corsé de Hierro",
	"Loaded Dice": "Dados Trucados",
	"Phoenix Feather": "Pluma de Fénix",
	"Cat-Eye Glasses": "Gafas Cat-Eye",
	"Spotlight": "Foco",
	"Fog Machine": "Máquina de Humo",
	"Vampire Fang": "Colmillo de Vampiro",
	"Venom Vial": "Vial de Veneno",
	"Gym Membership": "Abono del Gym",
	"Summons summon +1 Goon.": "Las invocaciones invocan +1 Goon.",
	"Gain 8 gold after each combat.": "+8 oro tras cada combate.",
	"Your Roast applies +1 stack.": "Tu Roast aplica +1 stack.",
	"+1 Energy each turn.": "+1 Energía por turno.",
	"Aura cards grant +1 Aura.": "Las cartas de Aura dan +1 Aura.",
	"When an enemy hits you, deal 3 back.": "Cuando te golpean, devuelve 3.",
	"Your attacks crit 15% of the time (x2 damage).": "Tus ataques critean el 15% (x2 daño).",
	"Your first spell each turn deals +3.": "Tu primer hechizo del turno hace +3.",
	"Draw +1 card each turn.": "Roba +1 carta por turno.",
	"Every enemy starts combat Cooked (Vulnerable 1).": "Cada enemigo empieza Cooked (Vulnerable 1).",
	"+2 Aura income each turn.": "+2 de Aura por turno.",
	"Heal 3 at the start of each turn.": "Cura 3 al inicio de cada turno.",
	"Toxic you apply gets +1 stack.": "El Toxic que aplicas: +1 stack.",
	"Start each combat with 2 Rizz.": "Empieza cada combate con 2 Rizz.",
	# --- outfits ---
	"Apprentice Hat": "Sombrero de Aprendiz",
	"Bone Scepter": "Cetro de Hueso",
	"Catwalk Heels": "Tacones de Pasarela",
	"Char Wand": "Varita de Carbón",
	"Hype Charm": "Amuleto Hype",
	"Diva Heels": "Tacones de Diva",
	"Drip Robe": "Túnica de Drip",
	"Influencer Ring": "Anillo de Influencer",
	"Lucky Cap": "Gorra de la Suerte",
	"Lucky Charm": "Amuleto de la Suerte",
	"Phoenix Gown": "Túnica de Fénix",
	"Plain Wand": "Varita Simple",
	"Swag Cap": "Gorra Swag",
	"Robe of Excess": "Túnica del Exceso",
	"Showstopper Hat": "Sombrero Showstopper",
	"Smolder Boots": "Botas de Brasa",
	"Worn Boots": "Botas Gastadas",
	"At 12+ Aura: +1 Rizz/turn.": "Con 12+ Aura: +1 Rizz/turno.",
	"Start combat with 5 Block.": "Empieza con 5 Bloqueo.",
	"Hit back for 3 when struck.": "Devuelve 3 al ser golpeado.",
	"Attacks crit 10% of the time.": "Los ataques critean el 10%.",
	"Heal 3 each turn.": "Cura 3 por turno.",
	"Start combat with 3 Aura.": "Empieza con 3 Aura.",
	"First spell each turn: +3 dmg.": "Primer hechizo del turno: +3 daño.",
	# --- wardrobe / boutique ---
	"Hat": "Sombrero",
	"Robe": "Túnica",
	"Staff": "Bastón",
	"Boots": "Botas",
	"Trinket": "Amuleto",
	"OWNED": "EN POSESIÓN",
	"%s, the %s    —    pick your drip": "%s, la/el %s    —    elige tu drip",
	"THE FIT": "EL OUTFIT",
	"Aura income: +%d / turn": "Ingreso de Aura: +%d / turno",
	"Cards added to deck: %d": "Cartas añadidas: %d",
	"drip perks:": "perks de drip:",
	"  (none)": "  (ninguno)",
	"(nothing owned)": "(nada en posesión)",
	"let's get it": "¡vamos!",
	"THE DRESSING ROOM": "EL VESTIDOR",
	"(nothing)": "(nada)",
	"(nothing owned — the Boutique sells %s drip)": "(nada en posesión — la Boutique vende drip de %s)",
	"%d owned": "%d en posesión",
	"scroll for more drip": "scrollea para más drip",
	"click to jump to the %s rack": "clic para saltar al estante de %s",
	"+%d card": "+%d carta(s)",
	# --- combat HUD ---
	"THEIR TURN": "TURNO RIVAL",
	"TURN %d": "TURNO %d",
	"AURA  %d   (+%d/turn)": "AURA  %d   (+%d/turno)",
	"%s ≥6 +2dmg    %s ≥12 +draw    %s ≥18 pierce": "%s ≥6 +2daño    %s ≥12 +carta    %s ≥18 Pierce",
	"End Turn": "Terminar turno",
	# --- node screens (event / rest / shop / chest / reward choices) ---
	"Cop one (20g)": "Pilla una (20g)",
	"Dig through it": "Rebusca",
	"dip": "me piro",
	"Do the work": "Haz el trabajo",
	"Get Snatched": "Recórtate",
	"Hard pass": "Paso total",
	"I'm fine actually": "Estoy bien, gracias",
	"Keep it pushing": "Sigue tu camino",
	"Log Off": "Log Off",
	"Nope, weird": "Nope, raro",
	"Not worth it": "No vale la pena",
	"Pay in vitality": "Paga con vitalidad",
	"Take a sip": "Echa un trago",
	"Toss 15g, make a wish": "Tira 15g, pide un deseo",
	"Try the fit on": "Pruébate el fit",
	"yeet a card (%dg)": "yeet una carta (%dg)",
	"%d gold": "%d de oro",
	"SOLD": "VENDIDO",
	"BLOCKED %d": "BLOQUEADO %d",
	"Resume Run   (Act %d)": "Reanudar partida   (Acto %d)",
	# --- combat log lines (slang/keywords kept; connective text translated) ---
	"the opps pulled up: %s": "los opps han llegado: %s",
	"you're Toxic'd for %d": "estás Toxic por %d",
	"— Your turn %d  (+%d aura, now %d) —": "— Tu turno %d  (+%d aura, ahora %d) —",
	"— Your turn %d —": "— Tu turno %d —",
	"the squad multiplies: +%d Goon": "la squad crece: +%d Goon",
	"%s is ENRAGED: +%d Rizz": "%s está ENRAGED: +%d Rizz",
	"CRIT! that's lethal rizz": "¡CRIT! eso es lethal rizz",
	"your %d Goons threw hands for %d": "tus %d Goons repartieron por %d",
	"%s got Roasted for %d": "%s fue Roasted por %d",
	"%s is Toxic'd for %d": "%s está Toxic por %d",
	"%s went off — %d×%d (%d)": "%s se vino arriba — %d×%d (%d)",
	"%s threw hands for %d": "%s repartió por %d",
	"thorns! %s caught a fade for 3": "¡espinas! %s recibe 3",
	"%s restocked %d HP": "%s recupera %d PV",
	"%s is being unbothered (Block %d)": "%s está unbothered (Bloqueo %d)",
	"%s hit you with %s %d": "%s te dio con %s %d",
	"%s locked in: %s +%d": "%s locked in: %s +%d",
	"%s drained %d of your Aura": "%s te robó %d de Aura",
	"%s called backup: %s pulled up!": "%s pidió refuerzos: ¡llegó %s!",
	"you took an L.": "te llevas una L.",
	"You play %s": "Juegas %s",
	"%d dmg": "%d daño",
	"%d block": "%d bloqueo",
	"%d burn": "%d burn",
	"spent %d aura": "%d aura gastada",
	"pierced!": "¡pierced!",
	"CRIT!": "¡CRIT!",
	# --- banter (speech bubbles) — translatable lines; pure slang passes through ---
	"aura farming fr": "haciendo aura farming fr",
	"I'm so BACK": "he VUELTO",
	"the aura is auraing": "el aura está auraing",
	"we mogging rn": "estamos mogging ahora",
	"you're so cooked": "estás súper cooked",
	"couldn't be me": "a mí no me pasaría",
	"you fell off": "te caíste",
	"0 aura detected": "0 aura detectada",
	"stay mad bestie": "sigue enfadado bestie",
	"ngl your drip is mid": "ngl tu drip es mid",
	"bestie you ATE that": "bestie te lo COMISTE",
	"let me cook": "déjame cocinar",
	"touch grass? in THIS economy??": "¿touch grass? ¿en ESTA economía??",
	"no thoughts just drip": "sin pensamientos solo drip",
	"we stan a serve": "stanneamos un serve",
	"sheeeesh that's hard": "sheeeesh eso es hard",
	# --- The Critic (USP) ---
	"+2DMG": "+2 DAÑO",
	"DRAW": "ROBO",
	"PIERCE": "PERFORA",
	"— FINALE —": "— GRAN FINAL —",
	"THE CRITIC:  %s": "LA CRÍTICA:  %s",
	"THE CRITIC  %s": "LA CRÍTICA  %s",
	"THE CRITIC:  ": "LA CRÍTICA:  ",
	"The Critic": "La Crítica",
	"Heckler": "Abucheador",
	"— a VIP room opens ahead.": "— se abre una sala VIP.",
	"— a heckler's waiting in your next fight.": "— un abucheador espera en tu próxima pelea.",
	"S — serve. obsessed. devastating.": "S — serve. obsesión. demoledor.",
	"S — the giiirls are SERVING. iconic.": "S — las chicas están SIRVIENDO. icónico.",
	"A — ate. left a crumb on the plate.": "A — ate. dejaste una miga en el plato.",
	"A — a real look. almost made me clap.": "A — un look de verdad. casi aplaudo.",
	"B — mid showing, bestie. do better.": "B — actuación mid, bestie. esfuérzate.",
	"B — it was giving... fine. i guess.": "B — it was giving... bien. supongo.",
	"C — flop era. who told you that was giving?": "C — flop era. ¿quién dijo que eso era giving?",
	"C — boo. i've seen NPCs with more drip.": "C — buu. he visto NPCs con más drip.",
	# --- Phases 2-4: drift / encore / tax / trend ---
	"S — i felt that in my SOUL. headliner.": "S — lo sentí en el ALMA. cabeza de cartel.",
	"A — so close to perfect it's annoying.": "A — tan cerca de perfecto que molesta.",
	"B — i've seen worse. i've seen way better.": "B — he visto cosas peores. y mucho mejores.",
	"C — that wasn't a fit, that was a cry for help.": "C — eso no fue un look, fue una petición de ayuda.",
	"again? serve me something NEW.": "¿otra vez? sírveme algo NUEVO.",
	"ENCORE ×%d — the crowd wants MORE": "ENCORE ×%d — el público quiere MÁS",
	"BOOED OFF — you fell out of the spotlight (-%d Aura)": "ABUCHEADO — te caíste del foco (-%d Aura)",
	"ENCORE ×%d!": "¡ENCORE ×%d!",
	"BOOED!": "¡ABUCHEADO!",
	"%s taxed your hoard for %d": "%s gravó tu botín por %d",
	"%s wants to tax you but you're broke": "%s quiere gravarte pero estás sin blanca",
	"TREND: it's giving abundance  (+1 Aura/turn)": "TENDENCIA: it's giving abundancia  (+1 Aura/turno)",
	"TREND: flop era  (-1 Aura/turn)": "TENDENCIA: flop era  (-1 Aura/turno)",
	"TREND: going viral  (+1 Aura/turn)": "TENDENCIA: se vuelve viral  (+1 Aura/turno)",
	"Finisher. Spend ALL Aura. Deal Aura × (2 + Encore). The longer you held the spotlight, the bigger the bow.": "Finisher. Gasta TODA la Aura. Inflige Aura × (2 + Encore). Cuanto más aguantaste el foco, mayor la reverencia.",
	"Finisher. Spend ALL Aura. Deal Aura × 1.5 to ALL enemies.": "Finisher. Gasta TODA la Aura. Inflige Aura × 1,5 a TODOS los enemigos.",
	"Finisher. Spend ALL Aura. Deal Aura × 2 to one enemy and heal half the damage.": "Finisher. Gasta TODA la Aura. Inflige Aura × 2 a un enemigo y cúrate la mitad del daño.",
	"Finishers deal +50%. Low drip — you live for the cash-out, not the slow build.": "Los finisher hacen +50%. Poco drip — vives para el cash-out, no para la construcción lenta.",
	"High drip: a fat, steady Aura income. Live in the thresholds; hoard, don't dump.": "Mucho drip: un ingreso de Aura gordo y constante. Vive en los umbrales; acumula, no gastes.",
	# --- in-combat teaching layer (tooltips/intents) + sweep additions ---
	"%d gold  ·  treat yourself": "%d de oro  ·  date un capricho",
	"+Block": "+Bloqueo",
	"BIG L.": "BIG L.",
	"Energy": "Energía",
	"Aura": "Aura",
	"Gold": "Oro",
	"Spent to play cards; refills to max at the start of each turn.": "Se gasta para jugar cartas; se rellena al máximo al inicio de cada turno.",
	"Banked style — it persists the whole fight. 6+: +2 dmg · 12+: +1 draw · 18+: pierce · 24+: the Encore spotlight. Finishers spend it all.": "Estilo acumulado — dura todo el combate. 6+: +2 daño · 12+: +1 robo · 18+: perforante · 24+: el foco del Encore. Los finishers lo gastan todo.",
	"Run currency — spend it in shops on cards, removals, and relics.": "Moneda de la partida — gástala en tiendas en cartas, eliminaciones y reliquias.",
	"Absorbs incoming damage; resets at the start of your next turn.": "Absorbe el daño entrante; se reinicia al comienzo de tu próximo turno.",
	"Rizz — adds its value to the damage of every attack.": "Rizz — suma su valor al daño de cada ataque.",
	"Cooked — takes +50% damage while it lasts.": "Cooked — recibe +50% de daño mientras dure.",
	"Mid — deals 25% less damage while it lasts.": "Mid — inflige un 25% menos de daño mientras dure.",
	"Roasted — takes this much at the start of its turn, then ramps down 1. Ignores Block.": "Roasted — recibe esta cantidad al inicio de su turno, luego baja 1. Ignora el Bloqueo.",
	"Toxic — takes this much at turn start (ignores Block), then ramps down 1.": "Toxic — recibe esta cantidad al inicio del turno (ignora el Bloqueo), luego baja 1.",
	"Goons — at end of turn each hits a random enemy for 2, and they soak hits against you.": "Goons — al final del turno cada uno golpea a un enemigo al azar por 2, y absorben golpes por ti.",
	"Jinxed — −10% crit chance per stack.": "Jinxed — −10% de prob. de crítico por stack.",
	"Exposed — you gain 25% less Block while it lasts.": "Exposed — ganas un 25% menos de Bloqueo mientras dure.",
	"Locked In — gain this much Rizz at the start of each of your turns.": "Locked In — gana esta cantidad de Rizz al inicio de cada uno de tus turnos.",
	"Aura Farm — gain this much Aura at the start of each turn.": "Aura Farm — gana esta cantidad de Aura al inicio de cada turno.",
	"Hive — summon this many Goons each turn.": "Hive — invoca esta cantidad de Goons cada turno.",
	"Barrier — gain this much Block each turn.": "Barrier — gana esta cantidad de Bloqueo cada turno.",
	"Their next move": "Su próximo movimiento",
	"Attacks for %d.": "Ataca por %d.",
	"Attacks %d times for %d each (%d total).": "Ataca %d veces por %d cada una (%d en total).",
	"Braces for %d Block.": "Se protege con %d de Bloqueo.",
	"Heals %d HP.": "Cura %d PV.",
	"Hits you with %s %d. ": "Te golpea con %s %d. ",
	"Buffs itself: %s +%d.": "Se potencia: %s +%d.",
	"Drains %d of your Aura.": "Drena %d de tu Aura.",
	"Taxes %d Aura if you're hoarding above a threshold.": "Cobra %d de Aura si acumulas por encima de un umbral.",
	"Summons backup into the fight.": "Invoca refuerzos al combate.",
	"Bides its time.": "Espera su momento.",
	"No passive.": "Sin pasiva.",
	"Drip +%d Aura/turn.": "Drip +%d de Aura/turno.",
	"Act %d/%d": "Acto %d/%d",
	"Asc %d": "Asc %d",
	"Gold %d": "Oro %d",
	"Clout %d": "Clout %d",
	"deck (%d)": "mazo (%d)",
	"your deck  (%d cards)": "tu mazo  (%d cartas)",
	# --- onboarding + critic ceremony ---
	"YOUR HAND": "TU MANO",
	"AURA — BANKED STYLE": "AURA — ESTILO ACUMULADO",
	"THE CRITIC IS WATCHING": "LA CRÍTICA TE OBSERVA",
	"Play cards with Energy (top left). Attacks hit the marked target — click an enemy to switch. End Turn passes the spotlight.": "Juega cartas con Energía (arriba a la izquierda). Los ataques golpean al objetivo marcado — haz clic en un enemigo para cambiar. Terminar turno cede el foco.",
	"Aura builds every turn and persists all fight. Light the tiers — 6+: +2 damage, 12+: +1 card, 18+: attacks pierce. Crest 24 to hold the spotlight, then spend it ALL on a Finisher.": "El Aura crece cada turno y dura todo el combate. Enciende los niveles — 6+: +2 daño, 12+: +1 carta, 18+: ataques perforantes. Supera 24 para mantener el foco y luego gástala TODA en un Finisher.",
	"Every fight gets a grade: S, A, B or C — scored on how boldly you play your Aura. An S opens a VIP room ahead; a C sends a heckler. Don't just win. Win the room.": "Cada combate recibe una nota: S, A, B o C — según lo atrevido que juegues tu Aura. Una S abre una sala VIP; una C envía un abucheador. No solo ganes. Gánate a la sala.",
	"next": "siguiente",
	"got it — let's serve": "entendido — a servir",
	"She grades every fight live: S, A, B or C — scored on how boldly you play your Aura (peak reached, tiers lit, a clean finisher cash-out). An S opens a VIP room ahead; a C sends a heckler. Her taste drifts: repeat the same trick and it stops paying.": "Califica cada combate en vivo: S, A, B o C — según lo atrevido que juegues tu Aura (pico alcanzado, niveles encendidos, un cierre limpio con finisher). Una S abre una sala VIP; una C envía un abucheador. Su gusto cambia: repite el mismo truco y deja de pagar.",
	"she sent me. boo.": "ella me envió. buu.",
	"VIP ovation: +%d gold — she approved.": "Ovación VIP: +%d de oro — ella aprobó.",
	"because: peak Aura %d · %d tiers lit · %s": "porque: pico de Aura %d · %d niveles encendidos · %s",
	"clean cash-out finish": "cierre limpio con cash-out",
	"no finisher cash-out": "sin cash-out de finisher",
	"BIG W!   cop a card": "BIG W!   pilla una carta",
	"Critic score %d": "Puntuación de la Crítica %d",
	"(badge = number of enemies)": "(número = cantidad de enemigos)",
	# --- run-end / act-clear ceremony ---
	"BIG W — TOUR COMPLETE": "BIG W — GIRA COMPLETADA",
	"all 3 acts served. the city is talking about you.": "los 3 actos servidos. la ciudad habla de ti.",
	"the run ends here — but Clout is forever.": "la partida termina aquí — pero el Clout es para siempre.",
	"+%d Clout earned   (lifetime %d)": "+%d Clout ganado   (total %d)",
	"NEW UNLOCKS: %s": "NUEVOS DESBLOQUEOS: %s",
	"%s unlocks at %d Clout — you have %d": "%s se desbloquea con %d Clout — llevas %d",
	"Run it back": "¡Otra vez!",
	"Main Menu": "Menú principal",
	"enjoying the demo? every follow helps a solo dev:": "¿te gusta la demo? cada follow ayuda a un dev en solitario:",
	"follow on itch.io": "seguir en itch.io",
	"join the Discord": "únete al Discord",
	"report a bug": "reportar un bug",
	"ACT %d CLEARED": "ACTO %d SUPERADO",
	"the gauntlet escalates — deck, HP and relics carry over.": "la cosa se pone seria — mazo, PV y reliquias se conservan.",
	"onward — Act %d": "adelante — Acto %d",
	"scroll for more": "desplázate para ver más",
	"Skip": "Saltar",
	"PAUSED": "PAUSA",
	"Resume": "Reanudar",
	"Toggle Fullscreen": "Alternar pantalla completa",
	"Abandon Run": "Abandonar partida",
	"Abandon — sure?": "Abandonar — ¿seguro?",
	"Cmd+Ctrl+F toggles fullscreen": "Cmd+Ctrl+F cambia a pantalla completa",
	"SFX volume": "Volumen de efectos",
	"Music volume": "Volumen de música",
	"Screen shake & flashes:   %s": "Vibración y destellos:   %s",
	"elite loot:": "botín de élite:",
	"+passive": "+pasiva",
	"WORN": "PUESTO",
	"Adds %d cards to your deck.": "Añade %d cartas a tu mazo.",
	"The Pop-Up": "El Pop-Up",
	"Sketchy Merch Stand": "Puesto de Merch Sospechoso",
	"Collection": "Colección",
	"lifetime Clout %d   ·   to spend %d   ·   Critic score %d   ·   Ascension %d": "Clout total %d   ·   para gastar %d   ·   Puntuación de la Crítica %d   ·   Ascensión %d",
	"Cards unlocked: %d / %d": "Cartas desbloqueadas: %d / %d",
	"Fits owned: %d / %d": "Outfits en el armario: %d / %d",
	"Relic pool unlocked: %d / %d": "Reliquias desbloqueadas: %d / %d",
	"next unlock at %d lifetime Clout: %s": "próximo desbloqueo con %d Clout total: %s",
	"everything is unlocked — full drip achieved.": "todo desbloqueado — drip máximo conseguido.",
	"ready to serve": "lista para servir",
	"Sacrifice a Goon: gain 3 Aura.": "Sacrifica un Goon: gana 3 de Aura.",
	"Deal 4× their Roasted stacks.": "Inflige 4× sus cargas de Roasted.",
	"Deal 3 twice. (Two crit rolls.)": "Inflige 3 dos veces. (Dos tiradas de crítico.)",
	"Deal 3× their Roast. Then apply 3 Roast.": "Inflige 3× su Roast. Luego aplica 3 de Roast.",
	"Summon 1 Goon. Draw 1.": "Invoca 1 Goon. Roba 1.",
	"Roast for 8. Aura +2.": "Rostiza por 8. Aura +2.",
	"Deal 8 and gain 3 Rizz.": "Inflige 8 y gana 3 de Rizz.",
	"Sacrifice 3 Goons: deal 16 and gain 6 Aura.": "Sacrifica 3 Goons: inflige 16 y gana 6 de Aura.",
	"Pose: gain 2 Aura.": "Pose: gana 2 de Aura.",
	"Power. Gain +1 Aura at the start of each turn.": "Power. +1 de Aura al inicio de cada turno.",
	"Shuffle your discard into your draw pile. Draw 1. +2 Aura — vintage is IN.": "Baraja tu descarte en el mazo de robo. Roba 1. +2 Aura — lo vintage está IN.",
	"Keep your unplayed hand this turn. +2 Aura. post it tomorrow.": "Conserva tu mano sin jugar este turno. +2 Aura. publícalo mañana.",
	"Deal 3. Apply 1 Mid. devastating.": "Inflige 3. Aplica 1 Mid. devastador.",
	"Deal 4 to ALL enemies. so much love to give.": "Inflige 4 a TODOS los enemigos. tanto amor para dar.",
	"Block 5. +2 Aura. mirror said yes.": "Bloquea 5. +2 Aura. el espejo dijo que sí.",
	"Deal 4. Deal 8 instead if they're Mid. shooters shoot.": "Inflige 4. 8 si el objetivo está Mid. quien no arriesga no gana.",
	"+2 Rizz. +3 Aura. they don't even know yet.": "+2 Rizz. +3 Aura. todavía ni lo saben.",
	"Deal 5 to ALL enemies. +2 Aura. work the room.": "Inflige 5 a TODOS los enemigos. +2 Aura. trabaja la sala.",
	"you keep the hand — it's all part of the plan": "te quedas la mano — todo es parte del plan",
	"nothing left to peek — your piles are empty": "nada que mirar — tus pilas están vacías",
	"up next: %s": "a continuación: %s",
	"fresh rotation — the discard shuffles back in": "rotación fresca — el descarte se baraja de vuelta",
	"Draw %d": "Robo %d",
	"Discard %d": "Descarte %d",
	"Draw pile": "Mazo de robo",
	"Discard pile": "Pila de descarte",
	"%d cards. When it runs dry, your discard shuffles back in.": "%d cartas. Cuando se agota, tu descarte se baraja de vuelta.",
	"%d cards. Played and discarded cards land here.": "%d cartas. Las cartas jugadas y descartadas caen aquí.",
	"up next": "a continuación",
	"Upgrade a card: make it cheaper OR hit harder.": "Mejora una carta: más barata O más pegada.",
	"Sharper": "Más afilada",
	"Juicier": "Más jugosa",
	"Costs 1 less Energy. efficiency era.": "Cuesta 1 de Energía menos. era de la eficiencia.",
	"+2 to its damage, Block and heals. more of everything.": "+2 a su daño, Bloqueo y curación. más de todo.",
	"how does it glow up?": "¿cómo hace el glow up?",
	"it's serving a look and lowkey staring back. unsettling fr.": "está sirviendo un look y lowkey te devuelve la mirada. inquietante fr.",
	"50%: cop an artefact.\n50%: it bites you for 8.": "50%: consigues un artefacto.\n50%: te muerde por 8.",
	"dip. some risks ain't it.": "huye. hay riesgos que no valen la pena.",
	"It fits like a dream!": "¡Te queda como un sueño!",
	"Nothing new to wear — you pocket 30 gold instead.": "Nada nuevo que ponerte — te embolsas 30 de oro en su lugar.",
	"The mannequin BIT you! Lost 8 HP.": "¡El maniquí te MORDIÓ! Pierdes 8 PV.",
	"a hooded figure's got mystery cards. trust the process?": "una figura encapuchada tiene cartas misteriosas. ¿confías en el proceso?",
	"pay 20 gold for a random card.": "paga 20 de oro por una carta aleatoria.",
	"hold onto your coin.": "guárdate tus monedas.",
	"You bought a %s!": "¡Compraste %s!",
	"\"let's unpack that deck, bestie.\" cut one card from your deck for good.": "\"vamos a procesar ese mazo, bestie.\" elimina una carta para siempre.",
	"remove a card from your deck.": "elimina una carta de tu mazo.",
	"skip it, pocket 20 gold (copay refund).": "pásalo, embólsate 20 de oro (reembolso del copago).",
	"You ghost the session and pocket 20 gold. growth!": "Le haces ghosting a la sesión y te llevas 20 de oro. ¡crecimiento!",
	"release which card?": "¿qué carta sueltas?",
	"Released %s. you feel lighter.": "Soltaste %s. te sientes más liviano.",
	"a velvet box hums. \"trade a little vitality for a little power?\"": "una caja de terciopelo zumba. \"¿un poco de vitalidad por un poco de poder?\"",
	"lose 6 MAX HP, gain an artefact.": "pierde 6 PV MÁX, gana un artefacto.",
	"keep your health, walk away.": "conserva tu salud, aléjate.",
	"You trade 6 MAX HP. worth it?": "Cambias 6 PV MÁX. ¿valió la pena?",
	"Nothing answers the call — you find 40 gold instead.": "Nada responde a la llamada — encuentras 40 de oro en su lugar.",
	"suspiciously clean water, absolutely loaded with old coins.": "agua sospechosamente limpia, repleta de monedas viejas.",
	"heal 16 HP. hydration check.": "cura 16 PV. hidratación al día.",
	"manifest an artefact.": "manifiesta un artefacto.",
	"Refreshing! Healed 16 HP.": "¡Refrescante! Curaste 16 PV.",
	"The fountain grants your wish!": "¡La fuente concede tu deseo!",
	"No artefacts left — the water heals you 10 instead.": "No quedan artefactos — el agua te cura 10 en su lugar.",
	"dusty, ornate, lowkey humming. rummage or nah?": "polvoriento, recargado, lowkey zumbando. ¿hurgas o nah?",
	"60%: find 30 gold.\n40%: moths bite you for 7.": "60%: encuentras 30 de oro.\n40%: las polillas te muerden por 7.",
	"best not to disturb it.": "mejor no molestarlo.",
	"Jackpot! Found 30 gold stuffed in a pocket.": "¡Premio! 30 de oro escondidos en un bolsillo.",
	"Moths! They bite you for 7.": "¡Polillas! Te muerden por 7.",
	"You move on, none the worse.": "Sigues adelante, sin un rasguño.",
	"she's at a corner table, reviewing a matcha. she has DEFINITELY seen you.": "está en una mesa del rincón, reseñando un matcha. DEFINITIVAMENTE te ha visto.",
	"Send over a matcha (15g)": "Mándale un matcha (15g)",
	"she pre-writes a rave. VIP treatment next fight.": "pre-escribe una reseña gloriosa. trato VIP en la próxima pelea.",
	"Roast her latte order": "Rostiza su pedido de latte",
	"50%: she's amused (VIP).\n50%: offended (heckler).": "50%: le divierte (VIP).\n50%: se ofende (abucheador).",
	"Pretend you didn't see her": "Finge que no la viste",
	"eyes front. keep walking.": "mirada al frente. sigue caminando.",
	"She sips. She nods, slowly. Your next fight is pre-reviewed: VIP room ahead.": "Da un sorbo. Asiente, despacio. Tu próxima pelea ya tiene reseña: sala VIP en camino.",
	"A beat. Then she LAUGHS. \"okay. that was good.\" VIP room ahead.": "Una pausa. Y entonces se RÍE. \"okay. ese estuvo bueno.\" Sala VIP en camino.",
	"Her pen comes out. It's already writing. A heckler will attend your next fight.": "Saca el bolígrafo. Ya está escribiendo. Un abucheador asistirá a tu próxima pelea.",
	"two clipboard interns from the Critic's office. they're rating fits today.": "dos becarios con portapapeles de la oficina de la Crítica. hoy califican fits.",
	"Strike a pose": "Haz una pose",
	"your equipped drip decides the rating.": "tu drip equipado decide la calificación.",
	"Decline the cameras": "Rechaza las cámaras",
	"you owe interns nothing.": "no les debes nada a los becarios.",
	"The fit is RATED. 25 gold appearance fee, effective immediately.": "El fit queda CALIFICADO. 25 de oro por aparición, efectivo ya.",
	"\"...mid,\" they write, handing you 5 pity gold. the wardrobe remembers this.": "\"...mid\", escriben, dándote 5 de oro de lástima. el vestidor no olvidará esto.",
	"a guy with a speaker offers to gas you up. rates negotiable.": "un tipo con altavoz se ofrece a hypearte. tarifas negociables.",
	"Hire him (25g)": "Contrátalo (25g)",
	"+5 MAX HP. confidence is structural.": "+5 PV MÁX. la confianza es estructural.",
	"Dap him up and dip": "Chócala y lárgate",
	"the free sample: heal 6 HP.": "la muestra gratis: cura 6 PV.",
	"He announces you EVERYWHERE you go now. +5 MAX HP.": "Ahora te anuncia a DONDEQUIERA que vas. +5 PV MÁX.",
	"One (1) free compliment. Surprisingly effective — healed 6 HP.": "Un (1) cumplido gratis. Sorprendentemente efectivo — curaste 6 PV.",
	"backstage at a venue. finders keepers is the law of the land here.": "backstage de un local. aquí la ley es: el que lo encuentra, se lo queda.",
	"50%: 25 gold.\n30%: someone's card.\n20%: a mousetrap (6 HP).": "50%: 25 de oro.\n30%: la carta de alguien.\n20%: una ratonera (6 PV).",
	"what's lost can stay lost.": "lo perdido puede seguir perdido.",
	"25 gold, loose, at the bottom. the venue owes you nothing now.": "25 de oro, sueltos, en el fondo. el local ya no te debe nada.",
	"Someone lost a %s. tragic. it's yours now.": "Alguien perdió %s. trágico. ahora es tuyo.",
	"A mousetrap. For your protection, apparently. Lost 6 HP.": "Una ratonera. Por tu seguridad, aparentemente. Pierdes 6 PV.",
	"the wizard group chat is BEEFING at 3am. someone has to say something.": "el chat grupal de magos está EN GUERRA a las 3am. alguien tiene que decir algo.",
	"Drop the perfect meme": "Suelta el meme perfecto",
	"instant credibility. someone airdrops you a card.": "credibilidad instantánea. alguien te manda una carta por airdrop.",
	"Mute the chat": "Silencia el chat",
	"peace. quiet. heal 8 HP.": "paz. silencio. cura 8 PV.",
	"Devastating. Legendary. Someone airdrops you a %s in tribute.": "Devastador. Legendario. Alguien te manda %s por airdrop como tributo.",
	"You mute all 7 chats. The silence heals 8 HP. self-care undefeated.": "Silencias los 7 chats. El silencio cura 8 PV. el autocuidado invicto.",
	"Look at your next 3 cards — take one. manifest it.": "Mira tus próximas 3 cartas — toma una. manifiéstalo.",
	"your next %d cards — take one": "tus próximas %d cartas — toma una",
	"left is the top of the pile": "la izquierda es la parte de arriba del mazo",
	"you reach for %s": "alcanzas %s",
	"your hands are FULL — it stays in the pile": "tienes las manos LLENAS — se queda en el mazo",
	"permanent drip — sorted by who can serve it": "drip permanente — ordenado según quién puede servirlo",
	"for everyone": "para todo el mundo",
	"for %s": "para %s",
	"%d Clout": "%d Clout",
	"%d cards — yeeting removes one copy": "%d cartas — el yeet elimina una sola copia",
	"elite loot: %s — %s": "botín de élite: %s — %s",
	"Skip the cards": "Pasar de las cartas",
	"Your Goons attack their target right now. go go go.": "Tus Goons atacan a su objetivo YA. dale dale dale.",
	"Your Goons attack twice. crowd control, literally.": "Tus Goons atacan dos veces. control de masas, literal.",
	"Deal 2× their Toxic. they kept score.": "Inflige 2× su Toxic. llevaban la cuenta.",
	"Summon 2 Goons. they do all the work.": "Invoca 2 Goons. ellos hacen todo el trabajo.",
	"Deal 4, three times. (Three crit rolls.)": "Inflige 4, tres veces. (Tres tiradas de crítico.)",
	"Deal 2 to ALL, twice. flash. flash.": "Inflige 2 a TODOS, dos veces. flash. flash.",
	"Enemies enter the fight with 2 Toxic.": "Los enemigos entran a la pelea con 2 de Toxic.",
	"Start combat with 2 Goons.": "Empieza el combate con 2 Goons.",
	"Your Goons jump the weakest opp.": "Tus Goons saltan sobre el rival más débil.",
	"+12% crit chance.": "+12% de probabilidad de crítico.",
	"Crits refund 1 Energy.": "Los críticos devuelven 1 de Energía.",
	"Poses serve +1 Aura.": "Las poses sirven +1 de Aura.",
	"Your Goons gang up on the BIGGEST opp.": "Tus Goons se juntan contra el rival más GRANDE.",
	"Your crits serve +1 Aura.": "Tus críticos sirven +1 de Aura.",
}
