class_name LocDE
extends RefCounted
## German translations. Keeps the international Gen-Z slang (Rizz, Aura, Slay,
## Delulu, Sigma, Glow Up, Cooked, Mid, "it's giving"...) and the game keywords
## (Block, Goon, Roast/Roasted, Toxic) — translates the connective/narrative text.

const TABLE := {
	# --- menu / chrome ---
	"New Game": "Neues Spiel",
	"Continue": "Weiter",
	"Continue   (%d Clout)": "Weiter   (%d Clout)",
	"Options": "Optionen",
	"Exit Game": "Beenden",
	"a roguelike deckbuilder about drip": "ein Roguelike-Deckbuilder über Drip",
	"F11 toggles fullscreen": "F11 schaltet Vollbild um",
	"Back to Menu": "Zurück zum Menü",
	"Back": "Zurück",
	"Cancel": "Abbrechen",
	"Menu": "Menü",
	"Close": "Schließen",
	"Confirm Reset?": "Zurücksetzen bestätigen?",
	"Reset All Progress": "Fortschritt löschen",
	"Erase & Start Fresh": "Löschen & neu starten",
	"This wipes all unlocked clothes and Clout. Click again to confirm.": "Das löscht alle Klamotten und Clout. Nochmal klicken zum Bestätigen.",
	"Progress reset to a fresh start.": "Fortschritt auf Anfang zurückgesetzt.",
	"Starting a new game erases your unlocked clothes and Clout. Continue?": "Ein neues Spiel löscht deine Klamotten und Clout. Weiter?",
	# --- options ---
	"Fullscreen:   %s": "Vollbild:   %s",
	"Sound FX:   %s": "Soundeffekte:   %s",
	"Music:   %s": "Musik:   %s",
	"Language:   %s": "Sprache:   %s",
	"On": "An",
	"Off": "Aus",
	"Attack": "Angriff",
	"Skill": "Skill",
	"Power": "Kraft",
	"Deutsch": "Deutsch",
	"English": "English",
	"Español": "Español",
	# --- class select ---
	"pick your fighter — all your power is in the fit.    Clout to spend: %d": "wähl deinen Fighter — deine ganze Power steckt im Fit.    Clout zum Ausgeben: %d",
	"the %s": "der/die %s",
	"%d HP": "%d LP",
	"Locked — unlock at %d Clout  (you have %d earned)": "Gesperrt — freischalten bei %d Clout  (du hast %d verdient)",
	"Ascension 0 / %d  —  base difficulty": "Ascension 0 / %d  —  Basis-Schwierigkeit",
	"Ascension %d / %d  —  +%d%% enemy HP, +%d%% dmg, +%d Clout": "Ascension %d / %d  —  +%d%% Gegner-LP, +%d%% Schaden, +%d Clout",
	"Boutique  (spend Clout)": "Boutique  (Clout ausgeben)",
	# --- wizards ---
	"It Girl": "It-Girl",
	"Goth Bestie": "Goth Bestie",
	"Rizzard": "Rizzard",
	"manifests heat, roasts the opps, serves looks for Aura. lowkey a menace": "manifestiert Hitze, roastet die Opps, serviert Looks für Aura. lowkey eine Gefahr",
	"summons goons, sacrifices them for clout, steals aura. unbothered & moisturized": "beschwört Goons, opfert sie für Clout, klaut Aura. unbothered & moisturized",
	"stacks Rizz to crit harder — pure charisma, zero shame. it's giving unbothered": "stackt Rizz für härtere Crits — pures Charisma, null Scham. it's giving unbothered",
	# --- card descriptions (slang titles kept; connective text translated) ---
	"Deal 5.": "5 Schaden.",
	"Deal 4.": "4 Schaden.",
	"Deal 6.": "6 Schaden.",
	"Gain 9 Block.": "Erhalte 9 Block.",
	"Deal 4 to ALL opps.": "4 Schaden an ALLE Opps.",
	"Deal 2× their Roasted stacks.": "2× ihre Roasted-Stacks Schaden.",
	"Gain 5 Block. stay unbothered.": "Erhalte 5 Block. bleib unbothered.",
	"Cleanse debuffs. Gain 2 Rizz. delulu is the solulu.": "Reinige Debuffs. +2 Rizz. delulu is the solulu.",
	"Deal 4. Heal 3.": "4 Schaden. Heile 3.",
	"Deal 6. it's giving warm": "6 Schaden. it's giving warm",
	"Deal 5. pew pew": "5 Schaden. pew pew",
	"Deal 4. If they're Roasted, deal 4 more.": "4 Schaden. Wenn Roasted, 4 extra.",
	"Deal 8 to ALL opps. Aura +2.": "8 Schaden an ALLE Opps. Aura +2.",
	"Gain 2 Rizz. (Rizz = crit chance)": "+2 Rizz. (Rizz = Crit-Chance)",
	"Gain 6 Block. Aura +1.": "Erhalte 6 Block. Aura +1.",
	"Finisher. Spend ALL Aura. Deal Aura × 3.": "Finisher. Verbrauch ALLE Aura. Schaden = Aura × 3.",
	"Power: gain 3 Block at the start of every turn. rise and grind.": "Kraft: +3 Block zu Beginn jedes Zuges. rise and grind.",
	"Make them Cooked +1. Aura +1.": "Mach sie Cooked +1. Aura +1.",
	"Power: raise 1 Goon at the start of every turn. the squad grows.": "Kraft: beschwör 1 Goon zu Beginn jedes Zuges. die Squad wächst.",
	"Deal 5. Aura +2.": "5 Schaden. Aura +2.",
	"Roast for 4. Aura +1.": "Roast für 4. Aura +1.",
	"Roast for 5. Aura +2.": "Roast für 5. Aura +2.",
	"Gain 5 Block. gatekeeping my HP": "Erhalte 5 Block. gatekeeping my LP",
	"Deal 6. Gain 2 Rizz. feeling lucky?": "6 Schaden. +2 Rizz. feeling lucky?",
	"Sacrifice a Goon: deal 7, Aura +3.": "Opfer einen Goon: 7 Schaden, Aura +3.",
	"Summon 2 Goons. Aura +1.": "Beschwör 2 Goons. Aura +1.",
	"Power: gain 1 Rizz at the start of every turn. it just works.": "Kraft: +1 Rizz zu Beginn jedes Zuges. it just works.",
	"Draw 2 cards.": "Zieh 2 Karten.",
	"Summon 1 Goon. Aura +1.": "Beschwör 1 Goon. Aura +1.",
	"Gain 3 Rizz. Draw 1.": "+3 Rizz. Zieh 1.",
	"Gain 6 Block. Draw 1.": "Erhalte 6 Block. Zieh 1.",
	"Gain 5 Block.": "Erhalte 5 Block.",
	"Power: +2 Aura at the start of every turn. let it cook.": "Kraft: +2 Aura zu Beginn jedes Zuges. let it cook.",
	"Make them Mid +2. Gain 1 Rizz.": "Mach sie Mid +2. +1 Rizz.",
	"Deal 7. Heal 4.": "7 Schaden. Heile 4.",
	"Apply 4 Toxic. it ramps down each turn but it hurts.": "Gib 4 Toxic. sinkt jeden Zug, tut aber weh.",
	"Aura +3.": "Aura +3.",
	"Cleanse all debuffs. Gain 5 Block. reset your aura fr.": "Reinige alle Debuffs. +5 Block. reset deine Aura fr.",
	"Aura +2. Gain 3 Block.": "Aura +2. Erhalte 3 Block.",
	"Deal 4. Gain 1 Rizz.": "4 Schaden. +1 Rizz.",
	"Roast ALL opps for 3. Aura +1. everyone gets the smoke.": "Roast ALLE Opps für 3. Aura +1. alle kriegen den Smoke.",
	"ALL opps get Cooked 1 — they take +50%. Aura +1. no crops, no edits.": "ALLE Opps werden Cooked 1 — sie kassieren +50%. Aura +1. kein Crop, kein Edit.",
	"Block 3, +2 per Roast on your target. they cook, you moisturize.": "Block 3, +2 pro Roast auf deinem Ziel. sie kochen, du bleibst moisturized.",
	"Spend 8 Aura: deal 18. going public. it's official.": "Zahle 8 Aura: 18 Schaden. going public. es ist offiziell.",
	"Spend 6 Aura: deal 9 to ALL opps. a lil teaser before the reveal.": "Zahle 6 Aura: 9 Schaden an ALLE Opps. ein kleiner Teaser vorm Reveal.",
	"ALL opps take 2× their own Roast. Then Roast ALL for 2. every page is about you.": "ALLE Opps kassieren 2× ihren eigenen Roast. Dann Roast ALLE für 2. jede Seite handelt von dir.",
	"Gain 3 Block, +2 per Goon. ride or dies. emphasis on died.": "Erhalte 3 Block, +2 pro Goon. ride or dies. Betonung auf died.",
	"Deal 2. Draw 1. the streak stays alive.": "2 Schaden. Zieh 1. die Streak lebt.",
	"ALL opps get Mid 1 — they deal -25%. Pose: +2 Aura. reviewed the lobby. mid.": "ALLE Opps werden Mid 1 — sie machen -25%. Pose: +2 Aura. die Lobby reviewed. mid.",
	"Gain Ghosted = your Rizz (max 4): dodge that many hits this round. seen. no reply.": "Erhalte Ghosted = dein Rizz (max 4): weiche diese Runde so vielen Treffern aus. gesehen. keine Antwort.",
	"Deal 2× your Rizz. (then Rizz adds itself again. it's unspoken.)": "2× dein Rizz Schaden. (dann zählt Rizz nochmal drauf. it's unspoken.)",
	"Deal 2, five times. Pose: +2 Aura. five chances to be him.": "2 Schaden, fünfmal. Pose: +2 Aura. fünf Chancen, ER zu sein.",
	"Spends %d Aura": "Zahlt %d Aura",
	"GHOSTED — you left that hit on read": "GHOSTED — du hast den Treffer auf gelesen gelassen",
	"Velvet Rope: you left the spotlight on YOUR terms": "Samtkordel: du hast das Spotlight zu DEINEN Bedingungen verlassen",
	"Royalties: the hit keeps paying (+%d Aura)": "Tantiemen: der Hit zahlt weiter (+%d Aura)",
	"FAN BEHAVIOR — the crowd rushes the stage": "FAN BEHAVIOR — die Crowd stürmt die Bühne",
	"Closet Cleanout: pick ONE more to yeet": "Kleiderschrank-Detox: yeete NOCH eine",
	"The Publicist spun the review: C → B. no heckler, no flop era.": "Die PR-Agentin hat die Review gedreht: C → B. kein Heckler, keine Flop-Era.",
	"Done": "Fertig",
	"TREND: flop era  (Trendsetter: not YOUR era — 0 Aura/turn)": "TREND: Flop-Era  (Trendsetter: nicht DEINE Era — 0 Aura/Zug)",
	# --- enemies (plain names translated; meme/slang names kept) ---
	"Angry Toaster": "Wütender Toaster",
	"Cursed Mirror": "Verfluchter Spiegel",
	"Disgruntled Pigeon": "Mürrische Taube",
	"Feral Houseplant": "Wilde Zimmerpflanze",
	"Garden Gargoyle": "Garten-Gargoyle",
	"Garden Gnome": "Gartenzwerg",
	
	"Possessed Mannequin": "Besessene Schaufensterpuppe",
	"Possessed Router": "Besessener Router",
	"Possessed Wardrobe": "Besessener Kleiderschrank",
	"Sock Puppet": "Sockenpuppe",
	"Taxidermy Owl": "Ausgestopfte Eule",
	"Unhinged Housecat": "Durchgedrehte Hauskatze",
	"Vengeful Vending Machine": "Rachsüchtiger Automat",
	"Wi-Fi Gremlin": "WLAN-Gremlin",
	"Gym Rat": "Gym Rat",
	"Hater in the Replies": "Hater in den Replies",
	"Possessed Disco Ball": "Besessene Discokugel",
	"NPC Streamer": "NPC-Streamer",
	"Engagement Farmer": "Engagement-Farmer",
	"The IRS": "Das Finanzamt",
	"The Bouncer": "Der Türsteher",
	"The Talent Agent": "Der Talent-Agent",
	"The Critic's Intern": "Die Praktikantin der Kritikerin",
	"Off-Duty Bouncer": "Türsteher außer Dienst",
	"Beta Algorithm": "Beta-Algorithmus",
	"Red-Carpet Umbrella": "Roter-Teppich-Schirm",
	"Garnishes %d%% of your gold. Kill it before it flees to get a refund.": "Pfändet %d%% deines Goldes. Töte es, bevor es flieht, für die Rückerstattung.",
	"About to flee the fight — taking everything it stole with it.": "Will gleich fliehen — mit allem, was es gestohlen hat.",
	"%s garnished %d gold. straight to collections.": "%s hat %d Gold gepfändet. direkt ins Inkasso.",
	"%s audits you... you're already broke. embarrassing.": "%s prüft deine Bücher... du bist schon pleite. peinlich.",
	"%s files your case and DIPS with %d gold!": "%s schließt deine Akte und HAUT AB mit %d Gold!",
	"%s files your case and dips.": "%s schließt deine Akte und verduftet.",
	"your refund came through: +%d gold": "deine Rückerstattung ist da: +%d Gold",
	"Toxic — takes this much at turn start (ignores Block). Never fades: cleanse it or outlive it.": "Toxic — kassiert so viel zu Zugbeginn (ignoriert Block). Verblasst nie: reinigen oder überleben.",
	"Roasted — takes this much at the start of its turn, then burns DOWN 1. Ignores Block — detonate it while it's hot.": "Roasted — kassiert so viel zu Zugbeginn, brennt dann um 1 RUNTER. Ignoriert Block — zünde es, solange es heiß ist.",
	"Apply 3 Toxic. it never dies down. rumors are forever.": "Gib 3 Toxic. es klingt nie ab. Gerüchte sind für immer.",
	"rate it on itch ★": "auf itch bewerten ★",
	"the Critic gave you an %s — agree? a rating helps a solo dev:": "die Kritikerin gab dir ein %s — stimmst du zu? eine Bewertung hilft einem Solo-Dev:",
	"enjoying the demo? every rating helps a solo dev:": "gefällt dir die Demo? jede Bewertung hilft einem Solo-Dev:",
	"%s makes a call... no one picks up.": "%s telefoniert... niemand geht ran.",
	# --- artifacts ---
	"Bone Charm": "Knochen-Anhänger",
	"Designer Purse": "Designer-Handtasche",
	"Ember Pin": "Glut-Anstecker",
	"Ring of Excess": "Ring des Exzess",
	"Glitter Brooch": "Glitzer-Brosche",
	"Iron Corset": "Eisernes Korsett",
	"Loaded Dice": "Gezinkte Würfel",
	"Phoenix Feather": "Phönixfeder",
	"Cat-Eye Glasses": "Cat-Eye-Brille",
	"Spotlight": "Spotlight",
	"Fog Machine": "Nebelmaschine",
	"Vampire Fang": "Vampirzahn",
	"Venom Vial": "Gift-Fläschchen",
	"Gym Membership": "Fitness-Abo",
	"Summons summon +1 Goon.": "Beschwörungen beschwören +1 Goon.",
	"Gain 8 gold after each combat.": "+8 Gold nach jedem Kampf.",
	"Your Roast applies +1 stack.": "Dein Roast gibt +1 Stack.",
	"+1 Energy each turn.": "+1 Energie pro Zug.",
	"Aura cards grant +1 Aura.": "Aura-Karten geben +1 Aura.",
	"When an enemy hits you, deal 3 back.": "Wenn ein Gegner dich trifft, 3 zurück.",
	"Your attacks crit 15% of the time (x2 damage).": "Deine Angriffe critten zu 15% (x2 Schaden).",
	"Your first spell each turn deals +3.": "Dein erster Zauber pro Zug macht +3.",
	"Draw +1 card each turn.": "Zieh +1 Karte pro Zug.",
	"Every enemy starts combat Cooked (Vulnerable 1).": "Jeder Gegner startet Cooked (Vulnerable 1).",
	"+2 Aura income each turn.": "+2 Aura-Einkommen pro Zug.",
	"Heal 3 at the start of each turn.": "Heile 3 zu Beginn jedes Zuges.",
	"Toxic you apply gets +1 stack.": "Toxic, das du gibst, +1 Stack.",
	"Start each combat with 2 Rizz.": "Starte jeden Kampf mit 2 Rizz.",
	"Velvet Rope": "Samtkordel",
	"For You Page": "For You Page",
	"Celebration of Life": "Gedenkfeier",
	"The Publicist": "Die PR-Agentin",
	"Royalties": "Tantiemen",
	"Set Spray": "Fixierspray",
	"Backstage Pass": "Backstage-Pass",
	"Closet Cleanout": "Kleiderschrank-Detox",
	"Borrowed Designer": "Geliehener Designer",
	"You can never get Booed — leaving the spotlight costs no Aura. exit on YOUR terms.": "Du kannst nie ausgebuht werden — das Spotlight zu verlassen kostet keine Aura. Abgang zu DEINEN Bedingungen.",
	"Pop-Up prices are 20% off. if it's on sale it's basically free.": "Pop-Up-Preise sind 20% reduziert. wenn's im Sale ist, ist es quasi gratis.",
	"Card rewards offer 4 picks instead of 3. the algorithm KNOWS you.": "Kartenbelohnungen bieten 4 statt 3 zur Wahl. der Algorithmus KENNT dich.",
	"Each Goon you sacrifice tips +1 Aura on the way out. what a sendoff.": "Jeder geopferte Goon gibt +1 Aura zum Abschied. was für ein Sendoff.",
	"The Feed adores you — a Trend never LOWERS your Aura income. flop era? not yours.": "Der Feed liebt dich — ein Trend senkt nie dein Aura-Einkommen. Flop-Era? nicht deine.",
	"Once per act, a C grade is spun into a B — no heckler, no flop era. PR is magic.": "Einmal pro Akt wird ein C zu einem B gedreht — kein Heckler, keine Flop-Era. PR ist Magie.",
	"Finishers refund 25% of the Aura they spend. the hit keeps paying.": "Finisher erstatten 25% der ausgegebenen Aura. der Hit zahlt weiter.",
	"Keep up to 6 Block between turns. the look stays SET.": "Behalte bis zu 6 Block zwischen den Zügen. der Look sitzt.",
	"Your attacks pierce Block from 12 Aura instead of 18. walk right past security.": "Deine Angriffe durchbohren Block ab 12 Aura statt 18. einfach an der Security vorbei.",
	"Get Snatched at rest sites yeets 2 cards instead of 1. decluttering is a personality.": "Get Snatched an Rastplätzen yeetet 2 Karten statt 1. Ausmisten ist eine Persönlichkeit.",
	"Your hand never auto-discards (10-card cap still applies). delete NOTHING.": "Deine Hand wird nie automatisch abgeworfen (10-Karten-Limit bleibt). lösche NICHTS.",
	"The Critic never tires of your style — repeat finishes stay 100% fresh. she's obsessed with you.": "Die Kritikerin wird deinen Stil nie leid — Wiederholungen bleiben 100% frisch. sie ist literally obsessed.",
	"Your first Pose each turn commands an immediate Goon strike. the fans canNOT be controlled.": "Deine erste Pose pro Zug befiehlt sofort einen Goon-Angriff. die Fans sind NICHT zu bändigen.",
	"Start every combat with +12 Aura but Exposed 2 — the fit is borrowed and NOT insured.": "Starte jeden Kampf mit +12 Aura aber Exposed 2 — der Fit ist geliehen und NICHT versichert.",
	# --- outfits ---
	"Apprentice Hat": "Lehrlingshut",
	"Bone Scepter": "Knochenzepter",
	"Catwalk Heels": "Catwalk-Heels",
	"Char Wand": "Kohle-Zauberstab",
	"Hype Charm": "Hype-Anhänger",
	"Diva Heels": "Diva-Heels",
	"Drip Robe": "Drip-Robe",
	"Influencer Ring": "Influencer-Ring",
	"Lucky Cap": "Glücks-Cap",
	"Lucky Charm": "Glücksbringer",
	"Phoenix Gown": "Phönix-Robe",
	"Plain Wand": "Schlichter Stab",
	"Swag Cap": "Swag-Cap",
	"Robe of Excess": "Robe des Exzess",
	"Showstopper Hat": "Showstopper-Hut",
	"Smolder Boots": "Glut-Stiefel",
	"Worn Boots": "Abgetragene Stiefel",
	"At 12+ Aura: +1 Rizz/turn.": "Bei 12+ Aura: +1 Rizz/Zug.",
	"Start combat with 5 Block.": "Starte mit 5 Block.",
	"Hit back for 3 when struck.": "Schlag mit 3 zurück.",
	"Attacks crit 10% of the time.": "Angriffe critten zu 10%.",
	"Heal 3 each turn.": "Heile 3 pro Zug.",
	"Start combat with 3 Aura.": "Starte mit 3 Aura.",
	"First spell each turn: +3 dmg.": "Erster Zauber pro Zug: +3 Schaden.",
	# --- wardrobe / boutique ---
	"Hat": "Hut",
	"Robe": "Robe",
	"Staff": "Stab",
	"Boots": "Stiefel",
	"Trinket": "Schmuck",
	"OWNED": "BESITZT",
	"%s, the %s    —    pick your drip": "%s, der/die %s    —    wähl dein Drip",
	"THE FIT": "DAS FIT",
	"Aura income: +%d / turn": "Aura-Einkommen: +%d / Zug",
	"Cards added to deck: %d": "Karten im Deck: %d",
	"drip perks:": "Drip-Perks:",
	"  (none)": "  (keine)",
	"(nothing owned)": "(nichts vorhanden)",
	"let's get it": "los geht's",
	"THE DRESSING ROOM": "DIE UMKLEIDE",
	"(nothing)": "(nichts)",
	"(nothing owned — the Boutique sells %s drip)": "(nichts vorhanden — die Boutique verkauft %s-Drip)",
	"%d owned": "%d im Besitz",
	"scroll for more drip": "scroll für mehr Drip",
	"click to jump to the %s rack": "klicken: zum %s-Regal springen",
	"+%d card": "+%d Karte(n)",
	# --- combat HUD ---
	"THEIR TURN": "GEGNER AM ZUG",
	"TURN %d": "ZUG %d",
	"AURA  %d   (+%d/turn)": "AURA  %d   (+%d/Zug)",
	"%s ≥6 +2dmg    %s ≥12 +draw    %s ≥18 pierce": "%s ≥6 +2Schaden    %s ≥12 +Karte    %s ≥18 Pierce",
	"End Turn": "Zug beenden",
	# --- node screens (event / rest / shop / chest / reward choices) ---
	"Cop one (20g)": "Kauf eine (20g)",
	"Dig through it": "Durchwühlen",
	"dip": "abhauen",
	"Do the work": "Mach die Arbeit",
	"Get Snatched": "Lass dich snatchen",
	"Hard pass": "Hartes Nein",
	"I'm fine actually": "Mir geht's gut, echt",
	"Keep it pushing": "Weiterziehen",
	"Log Off": "Log Off",
	"Nope, weird": "Nope, creepy",
	"Not worth it": "Nicht der Rede wert",
	"Pay in vitality": "Mit Vitalität zahlen",
	"Take a sip": "Nimm 'nen Schluck",
	"Toss 15g, make a wish": "15g rein, was wünschen",
	"Try the fit on": "Fit anprobieren",
	"yeet a card (%dg)": "yeet eine Karte (%dg)",
	"%d gold": "%d Gold",
	"SOLD": "VERKAUFT",
	"BLOCKED %d": "GEBLOCKT %d",
	"Resume Run   (Act %d)": "Run fortsetzen   (Akt %d)",
	# --- combat log lines (slang/keywords kept; connective text translated) ---
	"the opps pulled up: %s": "die Opps sind aufgetaucht: %s",
	"you're Toxic'd for %d": "du bist Toxic'd für %d",
	"— Your turn %d  (+%d aura, now %d) —": "— Dein Zug %d  (+%d Aura, jetzt %d) —",
	"— Your turn %d —": "— Dein Zug %d —",
	"the squad multiplies: +%d Goon": "die Squad wächst: +%d Goon",
	"%s is ENRAGED: +%d Rizz": "%s ist ENRAGED: +%d Rizz",
	"CRIT! that's lethal rizz": "CRIT! das ist lethal Rizz",
	"your %d Goons threw hands for %d": "deine %d Goons haben zugeschlagen für %d",
	"%s got Roasted for %d": "%s wurde Roasted für %d",
	"%s is Toxic'd for %d": "%s ist Toxic'd für %d",
	"%s went off — %d×%d (%d)": "%s ist abgegangen — %d×%d (%d)",
	"%s threw hands for %d": "%s hat zugeschlagen für %d",
	"thorns! %s caught a fade for 3": "Dornen! %s kassiert 3",
	"%s restocked %d HP": "%s füllt %d LP auf",
	"%s is being unbothered (Block %d)": "%s bleibt unbothered (Block %d)",
	"%s hit you with %s %d": "%s trifft dich mit %s %d",
	"%s locked in: %s +%d": "%s locked in: %s +%d",
	"%s drained %d of your Aura": "%s klaut %d deiner Aura",
	"%s called backup: %s pulled up!": "%s ruft Backup: %s ist da!",
	"you took an L.": "du kassierst ein L.",
	"You play %s": "Du spielst %s",
	"%d dmg": "%d Schaden",
	"%d block": "%d Block",
	"%d burn": "%d Burn",
	"spent %d aura": "%d Aura ausgegeben",
	"pierced!": "pierced!",
	"CRIT!": "CRIT!",
	# --- banter (speech bubbles) — translatable lines; pure slang passes through ---
	"aura farming fr": "aura farmen fr",
	"I'm so BACK": "ich bin so BACK",
	"the aura is auraing": "die Aura auraet",
	"we mogging rn": "wir moggen grad",
	"you're so cooked": "du bist so cooked",
	"couldn't be me": "wär mir nie passiert",
	"you fell off": "du bist abgestürzt",
	"0 aura detected": "0 Aura erkannt",
	"stay mad bestie": "bleib mad bestie",
	"ngl your drip is mid": "ngl dein Drip ist mid",
	"bestie you ATE that": "bestie du hast das GESERVED",
	"let me cook": "lass mich kochen",
	"touch grass? in THIS economy??": "touch grass? in DIESER Wirtschaft??",
	"no thoughts just drip": "keine Gedanken nur Drip",
	"we stan a serve": "wir stannen einen Serve",
	"sheeeesh that's hard": "sheeeesh das ist hard",
	# --- The Critic (USP) ---
	"+2DMG": "+2 SCH",
	"DRAW": "ZIEHEN",
	"PIERCE": "DURCHBRUCH",
	"— FINALE —": "— FINALE —",
	"THE CRITIC:  %s": "DIE KRITIKERIN:  %s",
	"THE CRITIC  %s": "DIE KRITIKERIN  %s",
	"THE CRITIC:  ": "DIE KRITIKERIN:  ",
	"The Critic": "Die Kritikerin",
	"Heckler": "Zwischenrufer",
	"— a VIP room opens ahead.": "— ein VIP-Raum öffnet sich.",
	"— a heckler's waiting in your next fight.": "— ein Zwischenrufer wartet im nächsten Kampf.",
	"S — serve. obsessed. devastating.": "S — serve. besessen. vernichtend.",
	"S — the giiirls are SERVING. iconic.": "S — die giiirls SERVEN. ikonisch.",
	"A — ate. left a crumb on the plate.": "A — ate. ein Krümel blieb auf dem Teller.",
	"A — a real look. almost made me clap.": "A — ein echter Look. fast hätte ich geklatscht.",
	"B — mid showing, bestie. do better.": "B — mid Auftritt, bestie. streng dich an.",
	"B — it was giving... fine. i guess.": "B — it was giving... okay. schätze ich.",
	"C — flop era. who told you that was giving?": "C — flop era. wer hat gesagt das wäre giving?",
	"C — boo. i've seen NPCs with more drip.": "C — buh. ich kenne NPCs mit mehr Drip.",
	# --- Phases 2-4: drift / encore / tax / trend ---
	"S — i felt that in my SOUL. headliner.": "S — das hab ich in der SEELE gespürt. Headliner.",
	"A — so close to perfect it's annoying.": "A — so nah an perfekt, das nervt.",
	"B — i've seen worse. i've seen way better.": "B — schon Schlimmeres gesehen. auch viel Besseres.",
	"C — that wasn't a fit, that was a cry for help.": "C — das war kein Fit, das war ein Hilferuf.",
	"again? serve me something NEW.": "schon wieder? servier mir was NEUES.",
	"ENCORE ×%d — the crowd wants MORE": "ENCORE ×%d — der Saal will MEHR",
	"BOOED OFF — you fell out of the spotlight (-%d Aura)": "AUSGEBUHT — du bist aus dem Rampenlicht gefallen (-%d Aura)",
	"ENCORE ×%d!": "ENCORE ×%d!",
	"BOOED!": "AUSGEBUHT!",
	"%s taxed your hoard for %d": "%s hat deinen Hort um %d besteuert",
	"%s wants to tax you but you're broke": "%s will dich besteuern, aber du bist pleite",
	"TREND: it's giving abundance  (+1 Aura/turn)": "TREND: it's giving Überfluss  (+1 Aura/Zug)",
	"TREND: flop era  (-1 Aura/turn)": "TREND: flop era  (-1 Aura/Zug)",
	"TREND: going viral  (+1 Aura/turn)": "TREND: geht viral  (+1 Aura/Zug)",
	"Finisher. Spend ALL Aura. Deal Aura × (2 + Encore). The longer you held the spotlight, the bigger the bow.": "Finisher. Verbrauche ALLE Aura. Mach Aura × (2 + Encore). Je länger du im Rampenlicht standest, desto größer die Verbeugung.",
	"Finisher. Spend ALL Aura. Deal Aura × 1.5 to ALL enemies.": "Finisher. Verbrauche ALLE Aura. Mach Aura × 1,5 an ALLE Gegner.",
	"Finisher. Spend ALL Aura. Deal Aura × 2 to one enemy and heal half the damage.": "Finisher. Verbrauche ALLE Aura. Mach Aura × 2 an einen Gegner und heile die Hälfte des Schadens.",
	"Finishers deal +50%. Low drip — you live for the cash-out, not the slow build.": "Finisher machen +50%. Wenig Drip — du lebst für den Cash-out, nicht den langsamen Aufbau.",
	"High drip: a fat, steady Aura income. Live in the thresholds; hoard, don't dump.": "Viel Drip: ein fettes, stetiges Aura-Einkommen. Lebe in den Schwellen; horte, dump nicht.",
	# --- in-combat teaching layer (tooltips/intents) + sweep additions ---
	"%d gold  ·  treat yourself": "%d Gold  ·  gönn dir",
	"+Block": "+Block",
	"BIG L.": "BIG L.",
	"Energy": "Energie",
	"Aura": "Aura",
	"Gold": "Gold",
	"Spent to play cards; refills to max at the start of each turn.": "Wird zum Ausspielen von Karten verbraucht; füllt sich zu Beginn jedes Zugs wieder auf.",
	"Banked style — it persists the whole fight. 6+: +2 dmg · 12+: +1 draw · 18+: pierce · 24+: the Encore spotlight. Finishers spend it all.": "Gebankter Style — bleibt den ganzen Kampf. 6+: +2 Schaden · 12+: +1 Karte · 18+: durchschlagend · 24+: das Encore-Rampenlicht. Finisher geben alles aus.",
	"Run currency — spend it in shops on cards, removals, and relics.": "Run-Währung — gib sie in Shops für Karten, Entfernen und Relikte aus.",
	"Absorbs incoming damage; resets at the start of your next turn.": "Absorbiert eingehenden Schaden; setzt sich zu Beginn deines nächsten Zugs zurück.",
	"Rizz — adds its value to the damage of every attack.": "Rizz — addiert seinen Wert auf den Schaden jedes Angriffs.",
	"Cooked — takes +50% damage while it lasts.": "Cooked — erleidet +50% Schaden, solange es anhält.",
	"Mid — deals 25% less damage while it lasts.": "Mid — verursacht 25% weniger Schaden, solange es anhält.",
	"Roasted — takes this much at the start of its turn, then ramps down 1. Ignores Block.": "Roasted — erleidet so viel zu Beginn seines Zugs, dann -1 pro Zug. Ignoriert Block.",
	"Toxic — takes this much at turn start (ignores Block), then ramps down 1.": "Toxic — erleidet so viel zu Zugbeginn (ignoriert Block), dann -1 pro Zug.",
	"Goons — at end of turn each hits a random enemy for 2, and they soak hits against you.": "Goons — am Zugende schlägt jeder einen zufälligen Gegner für 2, und sie fangen Treffer für dich ab.",
	"Jinxed — −10% crit chance per stack.": "Jinxed — −10% Crit-Chance pro Stack.",
	"Exposed — you gain 25% less Block while it lasts.": "Exposed — du erhältst 25% weniger Block, solange es anhält.",
	"Locked In — gain this much Rizz at the start of each of your turns.": "Locked In — erhalte so viel Rizz zu Beginn jedes deiner Züge.",
	"Aura Farm — gain this much Aura at the start of each turn.": "Aura Farm — erhalte so viel Aura zu Beginn jedes Zugs.",
	"Hive — summon this many Goons each turn.": "Hive — beschwöre so viele Goons pro Zug.",
	"Barrier — gain this much Block each turn.": "Barrier — erhalte so viel Block pro Zug.",
	"Ghosted — dodges the next N attack hits against you. Gone at the start of your next turn.": "Ghosted — weicht den nächsten N Angriffstreffern gegen dich aus. Weg zu Beginn deines nächsten Zuges.",
	"Their next move": "Ihr nächster Zug",
	"Attacks for %d.": "Greift für %d an.",
	"Attacks %d times for %d each (%d total).": "Greift %d-mal für je %d an (%d gesamt).",
	"Braces for %d Block.": "Wappnet sich mit %d Block.",
	"Heals %d HP.": "Heilt %d LP.",
	"Hits you with %s %d. ": "Trifft dich mit %s %d. ",
	"Buffs itself: %s +%d.": "Stärkt sich: %s +%d.",
	"Drains %d of your Aura.": "Saugt %d deiner Aura ab.",
	"Taxes %d Aura if you're hoarding above a threshold.": "Besteuert %d Aura, wenn du über einer Schwelle hortest.",
	"Summons backup into the fight.": "Ruft Verstärkung in den Kampf.",
	"Bides its time.": "Wartet ab.",
	"No passive.": "Kein Passiv.",
	"Drip +%d Aura/turn.": "Drip +%d Aura/Zug.",
	"Act %d/%d": "Akt %d/%d",
	"Asc %d": "Asc %d",
	"Gold %d": "Gold %d",
	"Clout %d": "Clout %d",
	"deck (%d)": "Deck (%d)",
	"your deck  (%d cards)": "dein Deck  (%d Karten)",
	# --- onboarding + critic ceremony ---
	"YOUR HAND": "DEINE HAND",
	"AURA — BANKED STYLE": "AURA — GEBANKTER STYLE",
	"THE CRITIC IS WATCHING": "DIE KRITIKERIN SCHAUT ZU",
	"Play cards with Energy (top left). Attacks hit the marked target — click an enemy to switch. End Turn passes the spotlight.": "Spiel Karten mit Energie (oben links). Angriffe treffen das markierte Ziel — klick einen Gegner zum Wechseln. Zug beenden gibt das Rampenlicht ab.",
	"Aura builds every turn and persists all fight. Light the tiers — 6+: +2 damage, 12+: +1 card, 18+: attacks pierce. Crest 24 to hold the spotlight, then spend it ALL on a Finisher.": "Aura wächst jeden Zug und bleibt den ganzen Kampf. Zünde die Stufen — 6+: +2 Schaden, 12+: +1 Karte, 18+: Angriffe durchschlagen. Knack die 24 fürs Rampenlicht, dann gib ALLES mit einem Finisher aus.",
	"Every fight gets a grade: S, A, B or C — scored on how boldly you play your Aura. An S opens a VIP room ahead; a C sends a heckler. Don't just win. Win the room.": "Jeder Kampf bekommt eine Note: S, A, B oder C — bewertet, wie mutig du deine Aura spielst. Ein S öffnet einen VIP-Raum; ein C schickt einen Zwischenrufer. Gewinn nicht nur. Gewinn den Saal.",
	"next": "weiter",
	"got it — let's serve": "verstanden — los serven",
	"She grades every fight live: S, A, B or C — scored on how boldly you play your Aura (peak reached, tiers lit, a clean finisher cash-out). An S opens a VIP room ahead; a C sends a heckler. Her taste drifts: repeat the same trick and it stops paying.": "Sie benotet jeden Kampf live: S, A, B oder C — bewertet, wie mutig du deine Aura spielst (Höchststand, gezündete Stufen, ein sauberer Finisher-Cash-out). Ein S öffnet einen VIP-Raum; ein C schickt einen Zwischenrufer. Ihr Geschmack driftet: derselbe Trick zahlt sich irgendwann nicht mehr aus.",
	"she sent me. boo.": "sie schickt mich. buh.",
	"VIP ovation: +%d gold — she approved.": "VIP-Ovation: +%d Gold — sie war angetan.",
	"because: peak Aura %d · %d tiers lit · %s": "weil: Aura-Peak %d · %d Stufen gezündet · %s",
	"clean cash-out finish": "sauberer Cash-out-Abschluss",
	"no finisher cash-out": "kein Finisher-Cash-out",
	"BIG W!   cop a card": "BIG W!   schnapp dir eine Karte",
	"Critic score %d": "Kritik-Score %d",
	"(badge = number of enemies)": "(Zahl = Anzahl Gegner)",
	# --- run-end / act-clear ceremony ---
	"BIG W — TOUR COMPLETE": "BIG W — TOUR GESCHAFFT",
	"all 3 acts served. the city is talking about you.": "alle 3 Akte geserved. die Stadt redet über dich.",
	"the run ends here — but Clout is forever.": "der Run endet hier — aber Clout ist für immer.",
	"+%d Clout earned   (lifetime %d)": "+%d Clout verdient   (insgesamt %d)",
	"NEW UNLOCKS: %s": "NEU FREIGESCHALTET: %s",
	"%s unlocks at %d Clout — you have %d": "%s wird bei %d Clout frei — du hast %d",
	"Run it back": "Nochmal!",
	"Main Menu": "Hauptmenü",
	"enjoying the demo? every follow helps a solo dev:": "gefällt dir die Demo? jeder Follow hilft einem Solo-Dev:",
	"follow on itch.io": "auf itch.io folgen",
	"join the Discord": "zum Discord",
	"report a bug": "Bug melden",
	"ACT %d CLEARED": "AKT %d GESCHAFFT",
	"the gauntlet escalates — deck, HP and relics carry over.": "es wird härter — Deck, LP und Relikte bleiben.",
	"onward — Act %d": "weiter — Akt %d",
	"scroll for more": "scrollen für mehr",
	"Skip": "Überspringen",
	"PAUSED": "PAUSE",
	"Resume": "Weiterspielen",
	"Toggle Fullscreen": "Vollbild umschalten",
	"Abandon Run": "Run aufgeben",
	"Abandon — sure?": "Aufgeben — sicher?",
	"Cmd+Ctrl+F toggles fullscreen": "Cmd+Ctrl+F schaltet Vollbild um",
	"SFX volume": "Effekt-Lautstärke",
	"Music volume": "Musik-Lautstärke",
	"Screen shake & flashes:   %s": "Bildschirmwackeln & Blitze:   %s",
	"elite loot:": "Elite-Beute:",
	"+passive": "+Passiv",
	"WORN": "GETRAGEN",
	"Adds %d cards to your deck.": "Fügt deinem Deck %d Karten hinzu.",
	"The Pop-Up": "Der Pop-Up",
	"Sketchy Merch Stand": "Zwielichtiger Merch-Stand",
	"Collection": "Sammlung",
	"lifetime Clout %d   ·   to spend %d   ·   Critic score %d   ·   Ascension %d": "Clout insgesamt %d   ·   zum Ausgeben %d   ·   Kritik-Score %d   ·   Ascension %d",
	"Cards unlocked: %d / %d": "Karten freigeschaltet: %d / %d",
	"Fits owned: %d / %d": "Fits im Schrank: %d / %d",
	"Relic pool unlocked: %d / %d": "Relikt-Pool freigeschaltet: %d / %d",
	"next unlock at %d lifetime Clout: %s": "nächste Freischaltung bei %d Clout insgesamt: %s",
	"everything is unlocked — full drip achieved.": "alles freigeschaltet — maximaler Drip erreicht.",
	"ready to serve": "bereit zu serven",
	"Sacrifice a Goon: gain 3 Aura.": "Opfere einen Goon: erhalte 3 Aura.",
	"Deal 4× their Roasted stacks.": "Mach 4× ihre Roasted-Stapel als Schaden.",
	"Deal 3 twice. (Two crit rolls.)": "Mach 2× 3 Schaden. (Zwei Crit-Würfe.)",
	"Deal 3× their Roast. Then apply 3 Roast.": "Mach 3× ihr Roast als Schaden. Verpasse danach 3 Roast.",
	"Summon 1 Goon. Draw 1.": "Beschwöre 1 Goon. Zieh 1.",
	"Roast for 8. Aura +2.": "Roaste für 8. Aura +2.",
	"Deal 8 and gain 3 Rizz.": "Mach 8 Schaden und erhalte 3 Rizz.",
	"Sacrifice 3 Goons: deal 16 and gain 6 Aura.": "Opfere 3 Goons: mach 16 Schaden und erhalte 6 Aura.",
	"Pose: gain 2 Aura.": "Pose: erhalte 2 Aura.",
	"Power. Gain +1 Aura at the start of each turn.": "Power. +1 Aura zu Beginn jeder Runde.",
	"Shuffle your discard into your draw pile. Draw 1. +2 Aura — vintage is IN.": "Mische deine Ablage in den Nachziehstapel. Zieh 1. +2 Aura — Vintage ist IN.",
	"Keep your unplayed hand this turn. +2 Aura. post it tomorrow.": "Behalte deine ungespielte Hand diese Runde. +2 Aura. poste es morgen.",
	"Deal 3. Apply 1 Mid. devastating.": "Mach 3 Schaden. Verpasse 1 Mid. vernichtend.",
	"Deal 4 to ALL enemies. so much love to give.": "Mach 4 Schaden an ALLEN Gegnern. so viel Liebe zu geben.",
	"Block 5. +2 Aura. mirror said yes.": "Block 5. +2 Aura. der Spiegel hat ja gesagt.",
	"Deal 4. Deal 8 instead if they're Mid. shooters shoot.": "Mach 4 Schaden. 8, wenn das Ziel Mid ist. wer wagt, gewinnt.",
	"+2 Rizz. +3 Aura. they don't even know yet.": "+2 Rizz. +3 Aura. sie wissen es nur noch nicht.",
	"Deal 5 to ALL enemies. +2 Aura. work the room.": "Mach 5 Schaden an ALLEN Gegnern. +2 Aura. bespiel den Raum.",
	"you keep the hand — it's all part of the plan": "du behältst die Hand — alles Teil des Plans",
	"nothing left to peek — your piles are empty": "nichts zum Spicken — deine Stapel sind leer",
	"up next: %s": "gleich dran: %s",
	"fresh rotation — the discard shuffles back in": "frische Rotation — die Ablage mischt sich zurück",
	"Draw %d": "Ziehen %d",
	"Discard %d": "Ablage %d",
	"Draw pile": "Nachziehstapel",
	"Discard pile": "Ablagestapel",
	"%d cards. When it runs dry, your discard shuffles back in.": "%d Karten. Ist er leer, mischt sich deine Ablage zurück.",
	"%d cards. Played and discarded cards land here.": "%d Karten. Gespielte und abgeworfene Karten landen hier.",
	"up next": "gleich dran",
	"Upgrade a card: make it cheaper OR hit harder.": "Werte eine Karte auf: billiger ODER mehr Wumms.",
	"Sharper": "Schärfer",
	"Juicier": "Saftiger",
	"Costs 1 less Energy. efficiency era.": "Kostet 1 Energie weniger. Effizienz-Ära.",
	"+2 to its damage, Block and heals. more of everything.": "+2 auf Schaden, Block und Heilung. mehr von allem.",
	"how does it glow up?": "wie glow'd sie up?",
	"it's serving a look and lowkey staring back. unsettling fr.": "es serviert einen Look und starrt lowkey zurück. unsettling, fr.",
	"50%: cop an artefact.\n50%: it bites you for 8.": "50%: copp ein Artefakt.\n50%: es beißt dich für 8.",
	"dip. some risks ain't it.": "dip. manche Risiken sind's einfach nicht.",
	"It fits like a dream!": "Es passt wie ein Traum!",
	"Nothing new to wear — you pocket 30 gold instead.": "Nichts Neues zum Anziehen — du steckst stattdessen 30 Gold ein.",
	"The mannequin BIT you! Lost 8 HP.": "Das Mannequin hat dich GEBISSEN! 8 LP verloren.",
	"a hooded figure's got mystery cards. trust the process?": "eine vermummte Gestalt hat Mystery-Karten. trust the process?",
	"pay 20 gold for a random card.": "zahl 20 Gold für eine zufällige Karte.",
	"hold onto your coin.": "behalt deine Münzen.",
	"You bought a %s!": "Du hast %s gekauft!",
	"\"let's unpack that deck, bestie.\" cut one card from your deck for good.": "\"lass uns das Deck mal aufarbeiten, Bestie.\" entferne eine Karte für immer.",
	"remove a card from your deck.": "entferne eine Karte aus deinem Deck.",
	"skip it, pocket 20 gold (copay refund).": "lass es, nimm 20 Gold (Zuzahlung zurück).",
	"You ghost the session and pocket 20 gold. growth!": "Du ghostest die Sitzung und nimmst 20 Gold. growth!",
	"release which card?": "welche Karte loslassen?",
	"Released %s. you feel lighter.": "%s losgelassen. du fühlst dich leichter.",
	"a velvet box hums. \"trade a little vitality for a little power?\"": "eine Samtbox summt. \"etwas Vitalität gegen etwas Macht?\"",
	"lose 6 MAX HP, gain an artefact.": "verliere 6 MAX-LP, erhalte ein Artefakt.",
	"keep your health, walk away.": "behalt deine Gesundheit, geh weiter.",
	"You trade 6 MAX HP. worth it?": "Du tauschst 6 MAX-LP. worth it?",
	"Nothing answers the call — you find 40 gold instead.": "Nichts antwortet — du findest stattdessen 40 Gold.",
	"suspiciously clean water, absolutely loaded with old coins.": "verdächtig sauberes Wasser, randvoll mit alten Münzen.",
	"heal 16 HP. hydration check.": "heile 16 LP. Hydration-Check.",
	"manifest an artefact.": "manifestiere ein Artefakt.",
	"Refreshing! Healed 16 HP.": "Erfrischend! 16 LP geheilt.",
	"The fountain grants your wish!": "Der Brunnen erfüllt deinen Wunsch!",
	"No artefacts left — the water heals you 10 instead.": "Keine Artefakte mehr — das Wasser heilt dich stattdessen um 10.",
	"dusty, ornate, lowkey humming. rummage or nah?": "staubig, verschnörkelt, summt lowkey. durchwühlen oder nah?",
	"60%: find 30 gold.\n40%: moths bite you for 7.": "60%: finde 30 Gold.\n40%: Motten beißen dich für 7.",
	"best not to disturb it.": "besser nicht stören.",
	"Jackpot! Found 30 gold stuffed in a pocket.": "Jackpot! 30 Gold in einer Tasche gefunden.",
	"Moths! They bite you for 7.": "Motten! Sie beißen dich für 7.",
	"You move on, none the worse.": "Du ziehst weiter, nichts passiert.",
	"she's at a corner table, reviewing a matcha. she has DEFINITELY seen you.": "sie sitzt am Ecktisch und reviewt einen Matcha. sie hat dich DEFINITIV gesehen.",
	"Send over a matcha (15g)": "Schick ihr einen Matcha (15g)",
	"she pre-writes a rave. VIP treatment next fight.": "sie schreibt vorab eine Lobeshymne. VIP-Behandlung im nächsten Kampf.",
	"Roast her latte order": "Roaste ihre Latte-Order",
	"50%: she's amused (VIP).\n50%: offended (heckler).": "50%: amüsiert (VIP).\n50%: beleidigt (Heckler).",
	"Pretend you didn't see her": "Tu so, als hättest du nichts gesehen",
	"eyes front. keep walking.": "Blick geradeaus. weitergehen.",
	"She sips. She nods, slowly. Your next fight is pre-reviewed: VIP room ahead.": "Sie nippt. Sie nickt, langsam. Dein nächster Kampf ist vorab reviewt: VIP-Raum voraus.",
	"A beat. Then she LAUGHS. \"okay. that was good.\" VIP room ahead.": "Eine Sekunde. Dann LACHT sie. \"okay. der saß.\" VIP-Raum voraus.",
	"Her pen comes out. It's already writing. A heckler will attend your next fight.": "Ihr Stift kommt raus. Er schreibt schon. Ein Heckler besucht deinen nächsten Kampf.",
	"two clipboard interns from the Critic's office. they're rating fits today.": "zwei Klemmbrett-Praktis aus dem Büro der Kritikerin. heute werden Fits bewertet.",
	"Strike a pose": "Wirf eine Pose",
	"your equipped drip decides the rating.": "dein angelegter Drip entscheidet die Wertung.",
	"Decline the cameras": "Lehn die Kameras ab",
	"you owe interns nothing.": "du schuldest Praktis gar nichts.",
	"The fit is RATED. 25 gold appearance fee, effective immediately.": "Der Fit ist RATED. 25 Gold Auftrittsgage, ab sofort.",
	"\"...mid,\" they write, handing you 5 pity gold. the wardrobe remembers this.": "\"...mid\", notieren sie und geben dir 5 Mitleids-Gold. die Garderobe vergisst das nicht.",
	"a guy with a speaker offers to gas you up. rates negotiable.": "ein Typ mit Box bietet an, dich zu hypen. Preise verhandelbar.",
	"Hire him (25g)": "Heuer ihn an (25g)",
	"+5 MAX HP. confidence is structural.": "+5 MAX-LP. Selbstbewusstsein ist tragend.",
	"Dap him up and dip": "Dap und dip",
	"the free sample: heal 6 HP.": "die Gratisprobe: heile 6 LP.",
	"He announces you EVERYWHERE you go now. +5 MAX HP.": "Er kündigt dich jetzt ÜBERALL an. +5 MAX-LP.",
	"One (1) free compliment. Surprisingly effective — healed 6 HP.": "Ein (1) Gratis-Kompliment. Überraschend effektiv — 6 LP geheilt.",
	"backstage at a venue. finders keepers is the law of the land here.": "Backstage in einem Club. wer's findet, behält's — so ist hier das Gesetz.",
	"50%: 25 gold.\n30%: someone's card.\n20%: a mousetrap (6 HP).": "50%: 25 Gold.\n30%: irgendwems Karte.\n20%: eine Mausefalle (6 LP).",
	"what's lost can stay lost.": "was verloren ist, kann verloren bleiben.",
	"25 gold, loose, at the bottom. the venue owes you nothing now.": "25 Gold, lose, ganz unten. der Club schuldet dir jetzt nichts mehr.",
	"Someone lost a %s. tragic. it's yours now.": "Jemand hat %s verloren. tragisch. gehört jetzt dir.",
	"A mousetrap. For your protection, apparently. Lost 6 HP.": "Eine Mausefalle. Angeblich zu deinem Schutz. 6 LP verloren.",
	"the wizard group chat is BEEFING at 3am. someone has to say something.": "der Zauberer-Gruppenchat BEEFT um 3 Uhr nachts. jemand muss was sagen.",
	"Drop the perfect meme": "Droppe das perfekte Meme",
	"instant credibility. someone airdrops you a card.": "sofortige Credibility. jemand airdroppt dir eine Karte.",
	"Mute the chat": "Mute den Chat",
	"peace. quiet. heal 8 HP.": "Ruhe. Frieden. heile 8 LP.",
	"Devastating. Legendary. Someone airdrops you a %s in tribute.": "Verheerend. Legendär. Jemand airdroppt dir %s als Tribut.",
	"You mute all 7 chats. The silence heals 8 HP. self-care undefeated.": "Du mutest alle 7 Chats. Die Stille heilt 8 LP. Self-Care undefeated.",
	"Look at your next 3 cards — take one. manifest it.": "Sieh dir deine nächsten 3 Karten an — nimm eine. manifestier es.",
	"your next %d cards — take one": "deine nächsten %d Karten — nimm eine",
	"left is the top of the pile": "links liegt oben auf dem Stapel",
	"you reach for %s": "du greifst nach %s",
	"your hands are FULL — it stays in the pile": "deine Hände sind VOLL — sie bleibt im Stapel",
	"permanent drip — sorted by who can serve it": "permanenter Drip — sortiert nach wer ihn serven kann",
	"for everyone": "für alle",
	"for %s": "für %s",
	"%d Clout": "%d Clout",
	"%d cards — yeeting removes one copy": "%d Karten — geyeeted wird genau eine Kopie",
	"elite loot: %s — %s": "Elite-Loot: %s — %s",
	"Skip the cards": "Karten auslassen",
	"Your Goons attack their target right now. go go go.": "Deine Goons greifen ihr Ziel SOFORT an. los los los.",
	"Your Goons attack twice. crowd control, literally.": "Deine Goons greifen zweimal an. Crowd-Control, wörtlich.",
	"Deal 2× their Toxic. they kept score.": "Mach 2× ihr Toxic als Schaden. sie haben mitgezählt.",
	"Summon 2 Goons. they do all the work.": "Beschwöre 2 Goons. die machen die ganze Arbeit.",
	"Deal 4, three times. (Three crit rolls.)": "Mach 3× 4 Schaden. (Drei Crit-Würfe.)",
	"Deal 2 to ALL, twice. flash. flash.": "Mach 2× 2 Schaden an ALLEN. klick. klick.",
	"Enemies enter the fight with 2 Toxic.": "Gegner starten den Kampf mit 2 Toxic.",
	"Start combat with 2 Goons.": "Starte den Kampf mit 2 Goons.",
	"Your Goons jump the weakest opp.": "Deine Goons stürzen sich auf den schwächsten Gegner.",
	"+12% crit chance.": "+12% Crit-Chance.",
	"Crits refund 1 Energy.": "Crits erstatten 1 Energie.",
	"Poses serve +1 Aura.": "Posen serven +1 Aura.",
	"Your Goons gang up on the BIGGEST opp.": "Deine Goons rotten sich gegen den GRÖSSTEN Gegner zusammen.",
	"Your crits serve +1 Aura.": "Deine Crits serven +1 Aura.",
}
